### ISSUE TITLE
Ruler display between users does not update when elevation is changed

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-elevation-ruler#1]
Currently, when a user updates the elevation, other users will not see any change to the ruler. Other users will see the change only once the first user moves the mouse (presumably triggering a measurement).

**Comment by Weissrolf** [comment]
The same applies for elevation changes done by the original user while the ruler is active. So when I have the ruler active while changing token elevation via keybind (module) then ER does not update its display until the mouse is moved.

On the other side ER *does* update its numbers immediately when its own keybinds [] are used. So the current triggers for updates seem to be mouse movement and manual keybinds, but changes to elevation are not recognized on their own.

**Comment by caewok** [comment]
Fixed in v0.6.0.
