### ISSUE TITLE
[Bug] Drawing Blocking Movement

### ISSUE THREAD

**Issue by Grandsome** [caewok/fvtt-elevation-ruler#108]
Drawings block movement in my game. Probably because there's no speed provider, I use WOD20 system, which has no speed integration yet. (I did write a module for speed integration for Drag Ruler but can't figure out how to do it with Elevation Ruler.)

Even if I move the movement slider it still blocks movement, maybe a switch could be implemented to turn on/off this feature.
Also, that feature could only be turned on if the drawing Role is set to "Object" rather than "Information".

Thanks.

**Comment by caewok** [comment]
I cannot replicate. When I add a drawing, it can be set to Object or Information and I can still set the Movement bonus/penalty. And I don't see drawings blocking movement. 

Are you running any other modules when this occurs? Are there any errors in the browser console?

**Comment by Jonoth777** [comment]
I have the same error, no other modules running except dependencies:

Foundry V12.329
PF2 V6.0.4
Browser: Chrome - 126.0.6478.127 (Official Build) - Latest at time of writing

Modules Enabled:
Elevation Ruler - 0.9.9
socketlib
routinglib

![image](https://github.com/user-attachments/assets/a0dd3dac-ab82-4b5e-9363-b3a73af273b9)


This occurs when there is a text drawing in the screen. Text drawing it set to information. No elevation, no movement penalty (set to 1).

**Comment by Grandsome** [comment]
Sorry for late reply, here's my console output:
![image](https://github.com/user-attachments/assets/60350ca5-97fb-4ac6-aa3c-0ffee9010ffc)
![image](https://github.com/user-attachments/assets/79d58c65-18a6-4339-9060-62f7a26d9b68)
![image](https://github.com/user-attachments/assets/acc78d0e-6528-48cf-8b94-5a735136d9bd)

Running same version as following ticket:
https://github.com/caewok/fvtt-elevation-ruler/issues/109#issuecomment-2244397563

**Comment by caewok** [comment]
I fixed the underlying issue about `a.rotate` not being a function. So while I could not directly replicate it, I hope that v0.9.11 resolves it.
