### ISSUE TITLE
[Possible Bug] libWrapper conflict with Baileywiki Mass Edit

### ISSUE THREAD

**Issue by Grandsome** [caewok/fvtt-elevation-ruler#109]
libWrapper complains about a conflict with Baileywiki Mass Edit module. I put Elevation ruler above Mass Edit to try to resolve the conflict, but this might need investigation.

Thanks.

**Comment by caewok** [comment]
In Foundry v12.328, Elevation Ruler v0.9.5, Mass Edit v1.7.0, dnd5e 3.2.1. I don't see any libWrapper complaints and I don't see any overlap between ER and Mass Edit. 

What versions are you using?

**Comment by Grandsome** [comment]
Sorry for late reply, had a bunch of games to prep. Here's the console output and my current versions:
![image](https://github.com/user-attachments/assets/c09eb688-08a0-473e-9727-da9b8398f2b5)
![image](https://github.com/user-attachments/assets/3c907913-b651-4114-8acb-3fdaf8ab8dd6)
![image](https://github.com/user-attachments/assets/83825e75-db05-4350-87f6-45a9fe6991c6)

**Comment by caewok** [comment]
For now, you can ignore these warnings. If there is an actual issue with how Baileywiki Mass Edit works when Elevation Ruler is present, these warnings might be helpful. But right now, it is just saying that they are more likely to conflict, not that they actually do conflict. As for the "chain the wrapper" warning, I cannot chain the wrapper in all situations there. The code is correct, near as I can tell. Thanks for posting the console output!
