### ISSUE TITLE
Ruler shows invisible Enemies plotted course

### ISSUE THREAD

**Issue by DMSei** [caewok/fvtt-elevation-ruler#112]
Foundry Version 11.315. Module Version 0.8.13. 

![Screenshot 2024-06-30 031551](https://github.com/caewok/fvtt-elevation-ruler/assets/112740873/83629f07-3966-481e-9579-e2cc832db04e)
![Screenshot 2024-06-30 031633](https://github.com/caewok/fvtt-elevation-ruler/assets/112740873/e62660f1-dfb0-4f73-8eac-8dc0c9adab38)

When I have a token that is supposed to be hidden. Neither Invisible, nor "Toggle Visibility State" hides the tokens movement. Tokens Disposition is set to Hostile in this image, however setting the disposition to Secret does not change anything. 

I have my settings configured to;
Levels Floor Label: Always
Tokens Block: Hostile only
Limit Pathfinding to Explored Areas: Checked
Use Token Ruler: Checked
Use Token Speed Highlighting: Always
No Speed Highlighting of Hostiles: Checked
Track Combat Move: Checked
Round Distance Multile: 0
Token as Terrain Multiplier: 2
Terrain Grid Measurement: Center Point
Percent Area Threshold: 0.5

Unchecking "No Speed Highlighting of Hostiles does not seem to impact anything. 
Changing "Use Token Speed Highlighting" to "Never" or "Combat Only" does not alter the issue.
Unchecking "Use Token Ruler" solves the issue, BUT then I as the DM/GM cannot see how fast/far my enemy is moving either.

**Comment by DMSei** [comment]
UPDATE: In Core>Configure Permissions. Disabling Game Master Permission to "Display Ruler Measurement" is a good temporary work around to this issue. But I would like to be able to measure things for my players using the ruler, and this disables that functionality.

**Comment by caewok** [comment]
Addressed in v0.9.6. Sorry, that may not be an immediate help to you in v11. But I changed the ruler broadcast in v12 so that it does not broadcast the ruler for token dragging when the token is invisible, hidden, or has secret disposition.

**Comment by DMSei** [comment]
> Addressed in v0.9.6. Sorry, that may not be an immediate help to you in v11. But I changed the ruler broadcast in v12 so that it does not broadcast the ruler for token dragging when the token is invisible, hidden, or has secret disposition.

Thanks for letting me know. Some of my Module suite does not yet support version 12, so I will have to deal with the work-around for now. Thank you kindly.
