### ISSUE TITLE
Add Support for wfrp4e

### ISSUE THREAD

**Issue by StevenEvans1966** [caewok/fvtt-elevation-ruler#113]
Looking at the API the code only supports movement multipliers from a base value.  wfrp4e uses two variables  

- actor.system.details.move.walk
- actor.system.details.move.run

run is >= walk 
here is some code I Wrote for Drag Ruler if that helps

```
class WFRPSpeedProvider extends SpeedProvider {
			get colors() {
				return [
					{ id: "walk", default: 0x00ff00, name: "walk" },
					{ id: "run", default: 0xffff00, name: "run" },
				];
			}

			getRanges(token) {
				const walkSpeedAttribute = this.getSetting("walkSpeedAttribute");

				if (!walkSpeedAttribute) return [];

				const tokenWalkSpeed = parseFloat(getProperty(token, walkSpeedAttribute));

				if (tokenWalkSpeed === undefined) {
					console.warn(`Drag Ruler (WFRPSpeedProvider) | The configured token speed attribute "${walkSpeedAttribute}" didn't return a speed value. To use colors based on drag distance set the setting to the correct value (or clear the box to disable this feature).`,);
					return [];
				}

				const runSpeedAttribute = this.getSetting("runSpeedAttribute");

				if (!runSpeedAttribute)
					return [{ range: tokenWalkSpeed, color: "walk" }];

				const tokenRunSpeed = parseFloat(getProperty(token, runSpeedAttribute));

				return [
					{ range: tokenWalkSpeed, color: "walk" },
					{ range: tokenRunSpeed, color: "run" },
				];
			}

			get settings() {
				return [
					{
						id: "walkSpeedAttribute",
						name: "walk",
						hint: "Walk Speed",
						scope: "world",
						config: true,
						type: String,
						default: "actor.system.details.move.walk",
					},
					{
						id: "runSpeedAttribute",
						name: "run",
						hint: "Run Speed",
						scope: "world",
						config: true,
						type: String,
						default: "actor.system.details.move.run",
					},
				];
			}
		}

		dragRuler.registerSystem("wfrp4e", WFRPSpeedProvider)
	}
```

**Comment by caewok** [comment]
Elevation Ruler already uses the default walk for wfrp4e, and then doubles it for "dash", which looks equivalent to run? Is that incorrect? Perhaps the run is not always simply double walk? If you can point me to the rules for walk/run, I could probably figure it out. But right now, I don't quite understand what is missing from ER's version.

**Comment by StevenEvans1966** [comment]
wfrp4e has Talents which modify walk and run separately from a Movement Attribute value.   simple run = walk * 2 approach will not work.  The core system handles calculating the 2 system.details.move values (system.details.move.walk & system.details.move.run)

just to give you an hint at complexity 
base rules are theses
Walk = Movement Attribute * 2
Run= Movement Attribute * 4

but the Talent Sprinter gives
Walk = Movement Attribute * 2
Run= (Movement Attribute +1) * 4

I have a player with an item that gives an additional multiplier on run of *2.
Walk = Movement Attribute * 2
Run= Movement Attribute * 8

encumbrance also effects movement  by giving -1 or -2 to  Movement Attribute or a multiplier of 0.

As you see wfrp4e requires the ruler to get values from system calculated variables.

**Comment by caewok** [comment]
Added in v0.9.7.
