### ISSUE TITLE
Elevation only calculated if starting at an elevation.

### ISSUE THREAD

**Issue by Danii0206** [caewok/fvtt-elevation-ruler#118]
Hi,

observed behaviour is this:

Case 1:
 Token A is at height 0.
 Token B is 10 ft away at height 30.

 Measure from A to B: 10 ft distance. 
 Measure from B to A: 35 ft distance.

Case 2:
 Token A is at heigt 5.
 Token B is 10 ft away at height 30.

 Measure from A to B: 30 ft distance.
 Measure from B to A: 30 ft distance.

Looks like height is only calculated if you start at a height other than 0.

**Comment by caewok** [comment]
Should be addressed in v0.9.7.
