### ISSUE TITLE
Distance not changing when using the hotkeys to change elevation. 

### ISSUE THREAD

**Issue by Danii0206** [caewok/fvtt-elevation-ruler#119]
Hi,

don't know if bug or feature.

Observed behaviour: 
 Measure a distance of lets say 10 ft.
 Press "]" to increase height by lets say 30 ft.
 Distance reads: 10 ft.

Expected behaviour: 
 Distance reads: 35 ft. (using diagonal measurements of 5-10-5)

**Comment by caewok** [comment]
Fixed in v0.9.7. Good catch!
