### ISSUE TITLE
Tokens become uninteractable after "Measure Distance" tool is used from arbitrary points.

### ISSUE THREAD

**Issue by BSDungeonmaster** [caewok/fvtt-elevation-ruler#120]
Foundry Version: V12, Build 327
System: Dnd 5e 3.2.1
Other Modules: N/A, issue occurs in isolation.

The module prohibits me from measuring the map without starting on top of a token. After attempting to use the core measure distance tool or shortcut (Ctrl+Left Mouse Drag), without starting from a token, the measurement will not be made and tokens can no longer be interacted with by either left or right click. You can measure starting from a token without issue.

Reloading the scene will re-enable token interaction and token ruler will once again work until the Measure Distance Tool is used.

I have turned off all other mods as well as tested with different Elevation Ruler Settings without change.

No relevant error messages were noted

**Comment by caewok** [comment]
Fixed in v0.9.7.
