### ISSUE TITLE
Measure Distance while Elevation Ruler activated stop all movement actions.

### ISSUE THREAD

**Issue by Tyberius2303** [caewok/fvtt-elevation-ruler#122]
Hello,

Hoping this is the right place or can get pointed in the right direction.
Recently moved to Elevation Ruler from Drag Ruler after the move to V12.
I've noticed that whenever the players and myself use the Measure Distance tool and it bends around corners i receive the attached error and most actions revolving around movement are now disabled.
![2024-07-02 19_27_38-Abandoned Farm • Foundry Virtual Tabletop](https://github.com/caewok/fvtt-elevation-ruler/assets/135076309/5393c4b1-95c8-4818-be0e-055e91401a28)
The error that shows mentioned the flag "terrainmapper" used by libWrapper i believe, apologies not great when it comes to troubleshooting.
Thanks in advanced!

Currently on Foundry V12.328
D&D 5e version 3.2.1

**Comment by caewok** [comment]
Fixed in v0.9.7.
