### ISSUE TITLE
PF2e difficult terrain should be +5 / +10 per square

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-elevation-ruler#125]
https://2e.aonprd.com/Rules.aspx?ID=2366

**Comment by Xirema** [comment]
Can confirm this also isn't working correctly for D&D5e if the "Diagonal Movement Rule" is set to Alternating (which is identical to the +5/+10 rule from PF2e).

![image](https://github.com/user-attachments/assets/810e6f80-a182-4eca-b72b-84a53c53f771)

**Comment by Lunchboxmaster777** [comment]
Agreed, the same this is happening to me for the alternating ruleset in DnD5e. Using Version 3.2.1 DnD and Foundry V12 (328)

**Comment by caewok** [comment]
I added options in v0.10.6 to impose a flat penalty for movement through tokens and movement through drawings. You probably also want make sure the new "Use Grid for Movement Penalties" setting in v0.10.6 is enabled. 

Note the current flat penalty is imposed per grid square. If you want the penalty to be larger if you are using alternating movement (i.e. impose +5 for a grid square for a "5" move but impose +10 for a grid square for a "10" move) please open a new issue. (That would be an entirely different option that I have not attempted to implement yet.)
