### ISSUE TITLE
Elevation changing too much when using the hotkeys to change elevation.

### ISSUE THREAD

**Issue by Danii0206** [caewok/fvtt-elevation-ruler#126]
Hi,

thank you for your fast response to my other bug reports. You are amazing!

Inputs: Measure 5ft to the right (or left, up, down) and press ] to increase height by 5 ft.

Observed output: `10ft [10ft]; ^5ft [@10ft]`
Expected output: `5ft [5ft]; ^5ft [@5ft]`
(Using Pf2e system.)

Looks like every 5 ft step in height gets added twice.

**Comment by caewok** [comment]
Fixed in v0.9.9.
