### ISSUE TITLE
Error when checking for updates

### ISSUE THREAD

**Issue by Sefotron** [caewok/fvtt-elevation-ruler#133]
![Screenshot 2024-07-08 085436](https://github.com/caewok/fvtt-elevation-ruler/assets/129655725/d1833f0e-20e9-4ca8-b62b-2d977783b2d7)

Been getting this error for a couple of days now when checking for updates in Foundry.

**Comment by jdwpom** [comment]
That looks like a problem for [this person](https://github.com/7H3LaughingMan/) who seems to have decided to cease development on the module? The [repository](https://github.com/7H3LaughingMan/pf2e-elevation-ruler/) is archived, potentially in favour of working on [their own ruler for PF2e](https://github.com/7H3LaughingMan/pf2e-ruler). You'd have to ask them directly.

**Comment by Sefotron** [comment]
Ah thanks!
