### ISSUE TITLE
[BUG] Token Ruler Drag Persisting

### ISSUE THREAD

**Issue by ItsDrafty** [caewok/fvtt-elevation-ruler#134]
Hello there,

I have only this module installed to test this. We noticed in our game, ever since the last update or so that when a player or GM drags their token, the ruler outline stays behind, making things really confusing and messy. 

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/123265319/5d4428ec-15f3-4a26-a806-98a5931436e2)

Hopefully this is an easy fix, thanks!

**Comment by jdwpom** [comment]
We've been having some lively discussion over in #124 about this, too.

**Comment by caewok** [comment]
Fixed in v0.9.9.
