### ISSUE TITLE
Possible to add support for metric units?

### ISSUE THREAD

**Issue by Zuricko** [caewok/fvtt-elevation-ruler#135]
I have been interested in using this add-on for my Symbaroum campaign, however most maps are measured in meters in that system. Typically PCs can move 10m, and each square is 2x2m. Any way you could add metric support, or a way for users to manually adjust the name of units and unit distance per square? Thanks!

**Comment by caewok** [comment]
You can do this by going to the Scene Configuration, in the Grid tab. Look for Grid Scale: distance and units. You might also want to go to the Elevation Ruler settings and change the "Round Distance to Multiple" to something other than 0.
