### ISSUE TITLE
Token Speed Highlighting only shows blue color

### ISSUE THREAD

**Issue by RulyTafzil** [caewok/fvtt-elevation-ruler#136]
This is with PF2e. It seems like the module is not reading the token speed correctly?
The Token Ruler only shows a light blue color when dragging the token.

Turning off Speed Highlighting, the token ruler changes to green.

**Comment by LJSmith066** [comment]
same, it uses player colour when speed highlighting is disabled and blue when it is enabled

**Comment by Dddsasul** [comment]
![Foundry_Virtual_Tabletop_PhJMbS4L4l](https://github.com/user-attachments/assets/d8709e2d-05a6-4f10-b93b-931f21c41d37)
I got that same behavior when using items that modify movement. This seems to be the cause for me.

**Comment by caewok** [comment]
Added the speed category logic from PF2E Elevation Ruler module in v0.9.10.

**Comment by Q-efx** [comment]
Hello,

the same problem exists in Starfinder in Foundry.
