### ISSUE TITLE
Using Foundry 'Measure Distance' tool to measure a line not starting on a controlled token breaks token control

### ISSUE THREAD

**Issue by dylan9397** [caewok/fvtt-elevation-ruler#139]
In Foundry 12-328 and D&D5e 3.2.1 anytime Elevation Ruler is enabled (tested with no other non-dependency plugins) using the 'Measure Distance' tool to measure any line which doesn't start on a selected token fails to draw the ruler and afterwards all tokens will be unmovable and the Measure Distance tool will be unusable. Tested some settings variations but not rigorously.

**Comment by caewok** [comment]
I cannot replicate this. Do you see any errors in the browser console? Is this a user doing the measuring or the GM?

**Comment by dylan9397** [comment]
We cannot replicate it today either, so I'm fine with closing this issue unless it comes back. It happened to both GM and every player account, and persisted through a server restart and numerous module activations/deactivations so I'm not sure sure what has changed. Don't have logs from when it happened unfortunately
