### ISSUE TITLE
Diagonal movement doesn't work on PF2e system

### ISSUE THREAD

**Issue by LucD20** [caewok/fvtt-elevation-ruler#14]
Windows 10
Pathfinder 2e System 4.6.5
Foundry V10 (Build 291)

The diagonal movements count as normal when moving up and down, as if with the 5/5/5 DnD5e system.

**Comment by caewok** [comment]
So the calculation of the total distance was borked when measuring horizontal or vertical. v0.6.4 should fix this. Thanks!
