### ISSUE TITLE
[Bug] The Token cannot move because it is locked.

### ISSUE THREAD

**Issue by bkw686** [caewok/fvtt-elevation-ruler#145]
I am using Elevation Ruler version 0.9.9 on Foundry version 12.328 with the Pathfinder 2e 6.0.4 system. I am accessing our server in the Firefox v127.0.2 (64-bit) browser on Windows 10, if that matters. Unfortunately, since I'm not the GM of the game, I'm unable to provide all world settings, but I will try to provide as much detail as I can as a player.

In short, Elevation Ruler seems to cause the error in the title when I try to move my token in one of the possible ways to move a token. The three methods that I typically use are the following:
1. Arrow keys
2. Left click and drag works fine
3. Ctrl+left click to measure out a path and space to make the token follow the path

If I use methods (1) and (2) on their own, I have no issues. If I use (3), the error in the title is triggered. If I attempt to use (1) and (2) after getting this error, the token refuses to move. If I refresh the browser after getting the error in the title, (1) and (2) work until I use (3) again.

My GM and I are pretty certain that Elevation Ruler is the issue, as we're able to return expected behavior once Elevation Ruler is turned off. I will note finally that, while I can replicate the issue on my end as a player, my GM is unable to find any issues on theirs, so it's possible that it might be a bug arising from the interaction between my browser, Foundry, and the module.

I also quickly went into the Console and this is the full detail of the error:

![image](https://github.com/user-attachments/assets/2f7234a6-d5e5-4230-bf1c-a83de1e73439)

**Comment by caewok** [comment]
I cannot make this error appear. When you say "ctrl+left click to measure out a path", what exactly are the steps you are taking there? Maybe I am not doing it the same.

**Comment by bkw686** [comment]
Sorry about the slow response. When I measure distance by making a chained ruler to determine a path for my token, then press space to make the token follow that path, I get the above error. Let me know if you need anything else from me to help debug.

**Comment by Arkemnos** [comment]
I have the exact same issue. When I push control to design the path I want my character to move, then I push spacebar to activate the movement, I have the message "This token cannot be moved because it's locked". 
Interesting bahavior : If I design the path using the 'mesure distance' ruler (instead of ctrl while on 'select token', I don't experience the same issue.

**Comment by Arkemnos** [comment]
I found an easier way to deal with the mod. I noticed that every player should activate the option "Use Token Ruler" in their own settings.

**Comment by aburley1234** [comment]
Also experiencing this issue, ctrl+ left drag over a token with the select token tool selected and then hit spacebar. It seems to only affect players not the GM.

**Comment by aburley1234** [comment]
Foundry Version 12.330
PF2E Version 6.2.1
Elevation Ruler 0.9.12

Might be related to https://github.com/caewok/fvtt-elevation-ruler/issues/130

**Comment by caewok** [comment]
Per @aburley1234's PR, this might be fixed in v0.10.0.
