### ISSUE TITLE
[Bug] Elevation Ruler completely locks up all movement after attempting to move a token

### ISSUE THREAD

**Issue by Lost-Soul13** [caewok/fvtt-elevation-ruler#147]
Attempting to move any token with Elevation Ruler active causes this error
![image](https://github.com/user-attachments/assets/ce9bc7e0-4c46-4ea6-9e5b-c888069ddca9)

Afterwards, moving the mouse cursor to any point on screen causes this error
![image](https://github.com/user-attachments/assets/963dae6d-352d-4ff3-ab31-19f153208f34)

And finally, if I manage to unselect the token by going to the measurement tools then back to the token tools, this error comes up every time I move the cursor over any token
![image](https://github.com/user-attachments/assets/974b86bb-e28f-4885-b488-2749d8ec8a9d)

**Comment by kiaric** [comment]
Can confirm this is also happening to me on v12.329

EDIT: New Pathfinder 2e system update added its own drag ruler functionality that seems to have thrown a wrench into things

**Comment by Grolm** [comment]
Same here.

**Comment by kiaric** [comment]
This may be fixed now as of [PF2e v6.1.11 ](https://github.com/foundryvtt/pf2e/releases/tag/6.1.1). Tried out the module and it seems to be working again. You can see that they changed how the drag measurement was implemented to better accommodate modules like this one. For people who still have the issue, try updating the game system and the PF2e elevation ruler integration, if you have it installed.

**Comment by caewok** [comment]
The underlying issue should be addressed in v0.9.10.
