### ISSUE TITLE
[Bug] Elevation reset when dragging token

### ISSUE THREAD

**Issue by eklan42** [caewok/fvtt-elevation-ruler#148]
Foundry 12.329
DnD 5e 3.3.0

Whenever I move a token, its elevation resets to zero.

**Comment by caewok** [comment]
I cannot replicate this. Do you see any errors in the browser console? What settings do you have in Elevation Ruler?

**Comment by eklan42** [comment]
Did you try it with the Foundry standalone application?

When I use Chrome v126 the bug does not appear as well. But with the Foundry app it does. There are no errors in the console though.

Here are my settings
![image](https://github.com/user-attachments/assets/a3246564-3857-46ea-8469-8e20ee0cdba5)

**Comment by caewok** [comment]
Closing as likely fixed in v0.10.
