### ISSUE TITLE
Bug: Elevation Does Not Adjust to Terrain Height

### ISSUE THREAD

**Issue by Vaizt** [caewok/fvtt-elevation-ruler#15]
I've tried every way I can think of to try to get this to work, but I simply can't reproduce it on a table where only the related modules are enabled. The current settings are based on the explanation given in the Foundry VTT Discord by Ironmonk. I have also tried reversing the values and even inverting them into the negatives just to see if that did anything at all.
![image](https://user-images.githubusercontent.com/91849051/215202461-0b88baa3-e316-4953-8dd1-451cbec1d8c2.png)
![image](https://user-images.githubusercontent.com/91849051/215202511-5a64bf38-e3c2-4280-881a-07f15d9d5766.png)

**Comment by caewok** [comment]
Fixed in v0.6.6.
