### ISSUE TITLE
[Feature Request] Add setting to completely disable pathfinding

### ISSUE THREAD

**Issue by nschoenwald** [caewok/fvtt-elevation-ruler#151]
Hi, I don't want to use Pathfinding in my games and would love to have an option to completely disable it for all users, including removing the toggle button.

**Comment by caewok** [comment]
Added in v0.9.10. Although I just realized that I didn't remove the toggl button, which I will do in the next version!

**Comment by nschoenwald** [comment]
Thank you so much!

**Comment by caewok** [comment]
Added the toggle removal in v0.9.11.
