### ISSUE TITLE
If autodetect elevation is disabled, don't drop the token elevation to 0 if the token is elevated.

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-elevation-ruler#155]

**Comment by caewok** [comment]
Added in v0.9.12.

**Comment by eklan42** [comment]
I see, that's the reason for issue #148 as well.

However this is not solved in v0.9.12. I guess the parantheses are missing after Settings.useAutoMoveDetection in Ruler.js line 161.

**Comment by caewok** [comment]
I think this is fixed in v0.10.
