### ISSUE TITLE
api feature: token.prevMoveDistance

### ISSUE THREAD

**Issue by n0q** [caewok/fvtt-elevation-ruler#158]
It would be quite convenient if you provided a `token.prevMoveDistance` which recorded how far a token moved last round. Games with more complicated movement rules could make use of this, rather than needing a work-around.

**Comment by caewok** [comment]
I already have that. If you want the last move distance, use `token.lastMoveDistance`.  If you are in combat, you probably want `token._combatMoveData`. Which, btw, is actually data stored on at `token.document.flags.elevationruler.movementHistory`. If you need to go back in time, you conceivably can do this by looking at the flag data for the token in Foundry's undo data.
