### ISSUE TITLE
Incorrect calculation of path in different directions

### ISSUE THREAD

**Issue by VirusNik21** [caewok/fvtt-elevation-ruler#159]
Hello, for some reason the pathfinding is different for two identical points in forward and reverse direction. See screenshots.
![2](https://github.com/user-attachments/assets/7fddc9d6-1f02-4804-ba10-a3ef06ced9e0)
![1](https://github.com/user-attachments/assets/88b00858-7f47-4566-80d5-b1b518e3f6e7)

**Comment by caewok** [comment]
This is mostly addressed now, particularly if the snap-to-grid pathfinding is enabled.
