### ISSUE TITLE
Elevation ruler with drag ruler enabled causing elevation drop

### ISSUE THREAD

**Issue by Symon-S** [caewok/fvtt-elevation-ruler#16]
When using elevation ruler with drag ruler enabled, elevations drop to zero when moving token.
This does not happen with either module diabled.
Tested systems: PF2e and DnD5e
Related issue on drag ruler <https://github.com/manuelVo/foundryvtt-drag-ruler/issues/253>
![Peek 2023-01-29 22-35](https://user-images.githubusercontent.com/81383360/215395706-133b95eb-1c9b-46fa-ba68-8fa9631a58de.gif)

**Comment by caewok** [comment]
Question: Does this still happen if you enable the preference in Elevation Ruler for "Add token elevation control"? Does it matter whether the added control, "Prefer token elevation," is enabled or not?

**Comment by Symon-S** [comment]
No change, with "Add token elevation control" enabled.
Also the "Prefer token elevation" added control does not appear to be available in either DnD5e or PF2e.
![image](https://user-images.githubusercontent.com/81383360/215690859-da550315-c1e4-40fb-adab-8f94a7c55aed.png)

**Comment by 9ryex5** [comment]
When you enable "Add token elevation control" it enables "Prefer token elevation" which is here 
![image](https://user-images.githubusercontent.com/43207603/229322876-bce59dbe-987e-41e3-a615-13bc81b665e8.png)
Toggling it on disables the behavior of dropping elevation when moving a token, it keeps the token elevation.

**Comment by Symon-S** [comment]
Well, seems like that was I was missing.
Thanks.
