### ISSUE TITLE
Request: Token Speed Highlighting for GURPS GGA 0.17.7

### ISSUE THREAD

**Issue by Farmeroz** [caewok/fvtt-elevation-ruler#160]
Thank you for an excellent module!

It works in most ways with GURPS GGA 0.17.7 https://github.com/crnormand/gurps except to Token Speed Highlighting.

In GURPS, your Move changes based on your Basic Move and then Encumbrance, and you can also "sprint".  This is best shown as a basic distance in hexes you can move as normal move (perhaps in green) and then an extra hex (perhaps in orange) for a "sprint" and then in red beyond that.  Elevation Ruler doesn't pick up on the Move score for the token so the colour never changes.

It also gives a negative number (in brackets) that doesn't seem to correspond to the GURPS range modifiers, it seems to increase by 1 a little early.  Not sure where it picks those numbers up from?

**Comment by caewok** [comment]
Added in v0.9.12. The negative number in brackets is the system, not ER, I think. I think it refers to the number of action points (or whatever is the GURPS equivalent) the move would cost?

**Comment by Farmeroz** [comment]
> Added in v0.9.12. The negative number in brackets is the system, not ER, I think. I think it refers to the number of action points (or whatever is the GURPS equivalent) the move would cost?

OMG!  Such speed and it's working beautifully!  Thank you *so* much! :-)
