### ISSUE TITLE
Elevation diagonals not measured correctly in 5-10-5

### ISSUE THREAD

**Issue by InsultingBagel** [caewok/fvtt-elevation-ruler#161]
Moving 5 feet up shouldn't incur any extra movement in the same way a single diagonal move doesn't incur any extra movement

![image](https://github.com/user-attachments/assets/56cae74d-5529-4421-900d-6a9755aa54b8)
![image](https://github.com/user-attachments/assets/dd65abc7-f2e8-473d-97dd-d4eccb272c36)
![image](https://github.com/user-attachments/assets/daa10d35-f596-4094-bb00-44a83ecc8432)

Below shows the drastic difference this is causing by contrasting moving diagonally across a 20 foot square in two different planes

![image](https://github.com/user-attachments/assets/1ea2196c-36ae-4db8-b2c0-d45623af445e)
![image](https://github.com/user-attachments/assets/12f7c307-dc96-49fb-a419-2b0a912ddbf8)

As shown in the second image, the correct distance should be 30 feet while the vertical measurement is suggesting 50ft

A method quickly calculating the correct distance is to simply add half the shorter distance rounded down to the nearest 5ft increment.

Moving 60 feet horizontally and 40 feet vertically would be 60+(40/2) = 80 feet
Moving 35 feet horizontally and 75 feet vertically would be (35/2) = 15, 15+75 = 90 feet

**Comment by caewok** [comment]
Good catch! Should be fixed in v0.9.12. It was basically doubling the elevation movement, so an issue not limited to 1-2-1 diagonal rule.

**Comment by PhyX-Meow** [comment]
This seems to be back in Foundry 331 and latest elevation ruler.
