### ISSUE TITLE
Request: In support of GURPS, use the Move when modified by Encumbrance

### ISSUE THREAD

**Issue by Farmeroz** [caewok/fvtt-elevation-ruler#164]
Firstly, thank you again so much for so quickly adding support for GURPS!  It's great!

In GURPS, you Move changes with your encumbrance level.  Some other modules pick this up, but Elevation Ruler currently seems to pick just the Base Move score, so it isn't dynamic with Encumbrance changes.

For this Actor, the Move is always showing as 7, but with each level of encumbrance is should decrease (so in this case it would be 5 at Light).

![image](https://github.com/user-attachments/assets/a1fb9441-7645-44ee-aacc-569b0c829305)

Is it possible for Elevation Ruler to do this?  Please let me know if you need any more details or information, and thank you in advance for looking at this.

**Comment by Battenhatch** [comment]
Came here to request this, so seconded. While the current implementation is a great step forward, there are some nuance and systems settings, that the system currently doesn't catch.

The GGA system modifies move en several ways, and ER atm. seem to work off the basic, unmodified move. Move cen be influenced by: Encumbrance, Injury level and Maneuver taken. GGA computes these and includes them in the table that Farmeroz has already shown. Thus, ER should be reading the move displayed in this table, from the highlighted column (which shows the influence of encumrance.

**Comment by Farmeroz** [comment]
I wanted to add, in case it helps, that the base attribute in GGA for the move `basicmove.value` but the one based on encumbrance and other modifiers is `currentmove`.

**Comment by caewok** [comment]
Added in v0.10.0. Thanks for the info; it was very helpful.
