### ISSUE TITLE
[Levels Module + Wall Height Module] Tokens on first floor or flying always try to move to ground level when moving.

### ISSUE THREAD

**Issue by Garsondee** [caewok/fvtt-elevation-ruler#174]
When I move my token up some stairs and increase their height to 10ft it works, but every movement seems to want to reset the height to 0ft. This means that flying tokens are always trying to return to the ground (which might be intentional) but it also means that characters which have gone upstairs in a building are always trying to move down through the floor, causing an error with every token move.

I'm absolutely loving the new Pathfinding which is a huge improvement BTW.

**Comment by Larkinabout** [comment]
Came to report the same:
![elevation-ruler-changing-elevation-on-move](https://github.com/user-attachments/assets/4b181e64-1bf6-453c-a5db-e7bd15d28846)

**Comment by Azamus** [comment]
same :(

**Comment by caewok** [comment]
Should be resolved in v0.10.2.
