### ISSUE TITLE
Distances are rounded up when "Round Distance to Multiple" is set to 0

### ISSUE THREAD

**Issue by Nolat** [caewok/fvtt-elevation-ruler#175]
Distances are rounded up (1.5 -> 2). This should not be the case, as the metric system uses 1.5 metres per square.

**Comment by Larkinabout** [comment]
Are you using gridless as there's a module setting to change the rounding? 0.5 works:
![image](https://github.com/user-attachments/assets/50320c0c-6efb-4918-9ef4-3d14b1f78be9)

**Comment by Nolat** [comment]
You're quite right, setting it to 0.5 works.
But the description says that setting it to 0 disables rounding, which is not the case.

**Comment by Larkinabout** [comment]
> But the description says that setting it to 0 disables rounding, which is not the case.

It's this line: https://github.com/caewok/fvtt-elevation-ruler/blob/b5b6a05b313ad2bffbc0e3a4f047caf10861f799/scripts/segment_labels_highlighting.js#L41

**Comment by caewok** [comment]
Should be resolved in v0.10.2.
