### ISSUE TITLE
Colors not showing when dragging, unable to move tokens

### ISSUE THREAD

**Issue by MaxswellSmart** [caewok/fvtt-elevation-ruler#178]
Foundry v12  330

When attempting to drag a token on the board, the token would not move. The image would look like it was going to move, but when the mouse was released, the token didn't move. Using arrow keys will allow for token movement.

Foundry's new! improved! ruler stinks. For some reason I cannot get it to show colors by distance.

I rolled back Elevation Ruler to 9.12 and it works correctly again.

**Comment by caewok** [comment]
Without more, there is nothing I can do here. If you are seeing some errors in the browser console (hit F12 in the browser) then perhaps there is something I can fix. Also check if this is happening with only Elevation Ruler and libWrapper active, or if there is another module conflicting.
