### ISSUE TITLE
Gridless maps error and nameplates size

### ISSUE THREAD

**Issue by TimorSol** [caewok/fvtt-elevation-ruler#183]
Hey! 
The recent update changed something in how Elevation Ruler works on gridless maps. Specifically, it stopped working. 
Whenever I try to move a token it just gives me some abstract number like 141 or 137. I got "Round Distance to Multiple" set to 1, which was an error somewhere in the past with gridded maps. 
Console spits out a RangeError error:
![obraz](https://github.com/user-attachments/assets/6fcd5333-6868-4234-8528-9dda0bfa64d5)

On gridded maps the nameplates became extremely small however. 
Example 1:
![obraz](https://github.com/user-attachments/assets/a08a2b11-db8d-4002-9a75-2fd053dbcd50)

No errors. 

![obraz](https://github.com/user-attachments/assets/82082e8a-b73c-484b-a678-dbef5ecbcbd7)

I imagine it might be because the default scaling values are set too low? (I did not change the config itself)

Running on Foundry v 12.331
Level Up: Advanced 5th Edition 0.19.24

**Comment by caewok** [comment]
Try updating to 0.10.3.

**Comment by caewok** [comment]
Also, v0.10.4 fixed an issue with measuring terrain cost on gridless maps.
