### ISSUE TITLE
Tokens not able to go down stairs

### ISSUE THREAD

**Issue by Commander-Fayne** [caewok/fvtt-elevation-ruler#185]
As seen in the gif. A token can properly go up the ramp (stairs) and it stops at the top to reset vision properly. However, when going back down the ramp, even though the token stops, the elevation of the token is no longer modified by the ramp region. 

![Ramp down missing!](https://github.com/user-attachments/assets/86d17353-77da-4e98-9a76-57986236fe10)

Foundry: 12.331
System: 3.3.1
Elevation Ruler: 0.10.4
Levels: 5.3.0
Terrain Mapper 0.4.1

![image](https://github.com/user-attachments/assets/d2de050d-d52d-4346-88fa-9fdefb9b272a)

![image](https://github.com/user-attachments/assets/6ef02d1e-5f7b-4483-8cf3-84fd8085b6e5)

![image](https://github.com/user-attachments/assets/5af6e1ef-a775-4e91-b56b-b4433c15266a)

![image](https://github.com/user-attachments/assets/c6436794-a000-45eb-b653-5c6ead4bb349)

![image](https://github.com/user-attachments/assets/6b41a7d9-3169-4e5e-a37f-daf1f1347b33)

The tiles for each floor (Ground set as the background, Floor 2 handled by Levels) are made correctly with alpha channel "holes" for where the stairs up to each location are. I've been making maps for use with Levels for years now, so I know I'm doing that part correctly. 

Anyway, if there's any fix for this or troubleshooting I could do, let me know. I know you just updated the Terrain Mapper module for the stairs function, but I want to use ramps for the stairs, not the instant teleportation of a token from ground to floor 2 when they touch a stair, mostly because I have larger castle maps with long stairs where fighting on them will take place.

**Comment by Commander-Fayne** [comment]
Update: Turned on the stairs region behavior, and going up is the same, but going down is even worse. See gif

![Ramp down missing2](https://github.com/user-attachments/assets/90222feb-a653-4271-99ac-6ba776e3c4d2)

Here is the region behavior
![image](https://github.com/user-attachments/assets/67522acd-85a3-4a1b-9e19-674b43a1d92f)

**Comment by Commander-Fayne** [comment]
Update 0.10.5 fixed this issue. Thanks!

**Comment by caewok** [comment]
Thanks for letting me know!
