### ISSUE TITLE
Ruler not showing up when dragged

### ISSUE THREAD

**Issue by MaxswellSmart** [caewok/fvtt-elevation-ruler#186]
When I attempt to drag a token, the colored ruler is not being displayed. The token will move as intended, but no colored squares.
Foundry v12.331  
PF2e v6.3.0
Elevation Ruler v0.10.4

So, I've done some digging with Find the Culprit. The only thing to come up was Workbench, but retesting several times has shown this conclusion to be inconclusive. =/
This error seems to be happening only on scenes with regions.
I've made the mistake of not providing enough information before, so hopefully this will help. I grabbed some images of the console, uploaded in order of grabs taken..
![Screenshot 2024-08-29 162209](https://github.com/user-attachments/assets/81948b88-9712-4cbb-9536-fac33b0eda3e)
![Screenshot 2024-08-29 162242](https://github.com/user-attachments/assets/ee183529-32d9-437e-a565-e27abf9a4864)
![Screenshot 2024-08-29 162311](https://github.com/user-attachments/assets/646d7de0-6e0d-4e39-a7a8-9b603a907b12)

**Comment by MaxswellSmart** [comment]
When all other mods, except libraries and Elevation Ruler, are disabled, the mod works like a dream. I just cannot figure out where the conflict lies.

**Comment by caewok** [comment]
You are in luck... Should be fixed in v0.10.5!
