### ISSUE TITLE
PF2e: Hexagonal grid results in NaN measurement

### ISSUE THREAD

**Issue by turthalion** [caewok/fvtt-elevation-ruler#188]
Foundry V12.331
PF2e 6.3.1
Elevation Ruler 0.10.5
libWrapper 1.12.15.0

With a hexagonal grid and Elevation Ruler and libWrapper the only enabled modules, distance always shows up as NaN.

If I flip to a square grid, it works fine.

Elevation ruler options are:
Use Pathfinding
Tokens Block No
Pathfinding Snap to Grid
Use Token Ruler
Hide GM Token Ruler
Use Token Speed Highlighting Always
Track Combat Move History
Round Distance to Multiple 0.1

![image](https://github.com/user-attachments/assets/cbe9b55b-713a-47de-8545-8bfaa6887171)
![image](https://github.com/user-attachments/assets/e7d6f0c0-da9e-44fc-8c31-0e4c3b8d0222)

**Comment by caewok** [comment]
Should be fixed in v0.10.6. Thanks!

**Comment by turthalion** [comment]
> Should be fixed in v0.10.6. Thanks!

Can confirm fix in v0.10.6. Thanks so much, love the comment on the [run](https://github.com/caewok/fvtt-elevation-ruler/actions/runs/10647809284)
