### ISSUE TITLE
Tokens with elevation pathing incorrectly with wall height same as their base height

### ISSUE THREAD

**Issue by Commander-Fayne** [caewok/fvtt-elevation-ruler#189]
When a token is at the elevation of a wall which is as tall as the token's elevation, it incorrectly attempts to pathfind around the wall. 

This token is at 10 ft, since it is on the second floor. The walls beneath it are using Wall Height module and are 0/10 ft. The token pathfinding is attempting to path around the walls beneath it because pathfinding considers those walls to be obstacles. 

Tokens should ideally ignore walls which are at their elevation or lower, since the wall would be floor level for the token at this elevation. 

![wall height incorrect pathing](https://github.com/user-attachments/assets/31b452f3-cfa4-4728-81de-baebee7546f5)

Foundry: 12.331
DnD5e: 3.3.1
Elevation Ruler: 0.10.5
Wall Height: 6.0.10
Levels: 5.3.4

**Comment by Commander-Fayne** [comment]
Current fix is to lower the height of the walls to at least 1 foot lower than the floor, but as there are some tokens taller than 9 ft and shorter than 10 ft, this is only a workaround and not an ideal solution.

**Comment by caewok** [comment]
Good catch. I fixed it in v0.10.6.
