### ISSUE TITLE
Feature Request: Prefer Token Elevation as a User Setting

### ISSUE THREAD

**Issue by Fair-Strides** [caewok/fvtt-elevation-ruler#19]
I don't know if it's intended or not, but it seems that the Prefer Token Elevation control needs to be toggled every time I start/refresh Foundry. I've got the button in my token toolbar on the left, but it's definitely bothering my players that every session things get iffy when they forget to toggle that button back to the "On" position.

**Comment by caewok** [comment]
Should be handled in v0.6.8. Thanks!
