### ISSUE TITLE
Waypoints not working or working unexpectedly

### ISSUE THREAD

**Issue by TimorSol** [caewok/fvtt-elevation-ruler#192]
The latest two (I believe) updates introduced some changes that broke the waypoint utility for me. In gridded maps it creates a indicator of the waypoint, but ignores it both visually and in the path aspect. 

On gridless maps it creates an odd waypoint super close to the initial starting spot. Video shows both issues. 

[2024-09-01+15-32-41.webm](https://github.com/user-attachments/assets/f1849e0e-9884-4e31-9f23-e67978326bad)

Foundry v12, a5e system, both up to date.

**Comment by caewok** [comment]
I cannot replicate this. Seems like a module conflict. Can you narrow down the modules that are active when this occurs and give me a list?

**Comment by TimorSol** [comment]
Ran Find the culprit and the results are in. 
I imagine it either has to be a system thing or setting thing in that case. 

[2024-09-02 23-37-57.webm](https://github.com/user-attachments/assets/64fba465-8e6c-4ad8-ac98-ede3c0a5c5a7)

**Comment by caewok** [comment]
Were you right-clicking to add waypoints? I fixed an issue with right-clicking in v0.10.9 that was adding the waypoint at the origin instead of at the click point.

**Comment by TimorSol** [comment]
Yes, it's the right-click. If I use a shortcut it works as intended. 

I have however managed to find the setting that is causing the issue: Pathfinding. If disabled, the waypoint functionality is working as intended.

**Comment by caewok** [comment]
Is this fixed in v0.10.10?

**Comment by TimorSol** [comment]
Seems like it works!

**Comment by caewok** [comment]
Great!
