### ISSUE TITLE
Incorrect calculation of elevation distance

### ISSUE THREAD

**Issue by AmoebaMan** [caewok/fvtt-elevation-ruler#194]
In the attached example, elevation is apparently not being included in the total distance calculation (10 ft) despite the elevation difference being correctly identified (+15 ft from 5 ft to 20 ft).

![image](https://github.com/user-attachments/assets/964bc30b-cf9a-484f-afab-a2b89f8c2e3b)

**Comment by caewok** [comment]
You are correct. I made some substantial changes in v0.10.7 to fix this.
