### ISSUE TITLE
Right clicking no longer creates waypoints

### ISSUE THREAD

**Issue by ScoflWorks** [caewok/fvtt-elevation-ruler#197]
As of v0.10.4 through v0.10.8, right clicking while using the token ruler no longer creates waypoints.

Tested with:
- Foundry 12.331
- DND5e 3.3.1
- Elevation Ruler 0.10.4

**Comment by sunyatacyte** [comment]
I have this issue also :)

**Comment by caewok** [comment]
Yep. It was adding a waypoint at the origin, which is not what we want! Try v0.10.9.
