### ISSUE TITLE
Movement penalty percent behavior is inverted

### ISSUE THREAD

**Issue by ScoflWorks** [caewok/fvtt-elevation-ruler#198]
When creating an area of movement penalty, the description of Movement Penalty Percent states to set the multiplier greater than 1 to impose a penalty and less than 1 to give a bonus (i.e. a value of 2 should double movement cost). However, the actual behavior of the module is inverted, with smaller values imposing a penalty and larger values granting a bonus (i.e. a value of 2 actually halves movement cost). The same applies for the Token Penalty Percent setting in the module settings.

![image](https://github.com/user-attachments/assets/917312b2-d482-4b4b-891b-f61b6c1da92c)

Tested with:
- Foundry 12.331
- DND5e 3.3.1
- Elevation Ruler 0.10.8

**Comment by caewok** [comment]
Yep, good catch! Fixed in v0.10.9.
