### ISSUE TITLE
Self referential dependency

### ISSUE THREAD

**Issue by zeel01** [caewok/fvtt-elevation-ruler#2]
There seems to be an error in the manifest, the libruler dependency lists the wrong manifest:

![image](https://user-images.githubusercontent.com/1721836/125968314-a9056895-4281-4353-adf9-200fc30a10cc.png)

That's *this* package. This causes foundry to repeatedly attempt to install libruler, actually re-install this package, ask to install libruler again, and repeat.

**Comment by caewok** [comment]
Good catch; thanks! Should be fixed with v0.2.2.
