### ISSUE TITLE
Incompatability with Drag Ruler and Elevated Vision

### ISSUE THREAD

**Issue by VladGrant** [caewok/fvtt-elevation-ruler#20]
The following errors exist when Drag Ruler is enabled, and you try to set waypoints (space while dragging), or if you move more than once in a combat turn:

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/12880220/c56e688a-9216-4aca-998c-082f17cf6a0d)

Meanwhile when I have Elevated Vision also enabled, players do not see the drag ruler at all and see the following errors, I actually see the player's drag ruler as a DM:

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/12880220/e7bc8304-3f66-4314-ab76-4b30967f947f)

**Comment by JoelF847** [comment]
I'm having different issues with drag ruler and elevated vision.  When most actors move using drag ruler, if they set a waypoint, the measurements change to NaN.  I have verified that if I disable elevated vision, the error doesn't happen.

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/149900118/0d052b02-db91-43db-a705-911e2bb7ea52)

**Comment by VladGrant** [comment]
@JoelF847 I used to see the exact same before, but kind of went with it, but now it's completely incompatible.

**Comment by caewok** [comment]
Unlikely to be fixed until this Drag Ruler [issue](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/310) is resolved.

But Elevation Ruler 0.7.4 adds options in settings to display the Foundry ruler when dragging tokens and to use different highlight colors based on token speed. There may still be some unresolved issues with Elevated Vision that I will look into.
