### ISSUE TITLE
Ruler doesn't ignore hidden tokens

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-elevation-ruler#200]
Basically, when the ruler is setup to either avoid hostiles or take a penalty to speed when going through tokens, it will not ignore hidden tokens. Happens a lot in default Adventure Paths that have tons of hidden Loot sheet tokens all over the maps.

**Comment by caewok** [comment]
How are you hiding the tokens?

**Comment by caewok** [comment]
Pathfinding as of v0.10.10 should ignore tokens that are marked not visible using the token hud. Let me know if you are using some other means to hide the token.

**Comment by NdranC** [comment]
[Screencast from 2024-09-09 17-52-54.webm](https://github.com/user-attachments/assets/4a5b33fd-1a4b-4462-8412-ad98e3b1300a)
![image](https://github.com/user-attachments/assets/a2c2293d-35a2-498c-8b19-bdd65862a0d0)
I downloaded the latest version and it doesn't seem to work?

I also wanted to add, that it might be worth it to also ignore tokens with the Undetected and Invisible status effect. Hidden and Concealed can remain as is because the player is supposed to still know what square they are located in, it only affects targeting.

**Comment by caewok** [comment]
Try uninstalling and reinstalling it. I wil add a new issue to add some config option to ignore tokens with certain status effects.

**Comment by NdranC** [comment]
Just uninstalling and immediately installing right back did nothing. I tested it again with just Elevation Ruler enabled and I still have the same issue. I also tried a monster token instead of the loot token. Same thing.

Yeah a configuration would probably be preferable but I though it might be too much work for you. Thank you!

**Comment by caewok** [comment]
I don't really understand your screencast. You never invoke pathfinding because you never drag the ruler through the token. Near as I can tell, pathfinding is not turning on, so it is working as expected. 

Is the issue that you want the ruler to not display the difficult terrain when moving through a hidden token?

**Comment by NdranC** [comment]
[Screencast from 2024-09-10 10-25-51.webm](https://github.com/user-attachments/assets/21631e07-a668-438a-ac2c-59f697bde701)
Both tokens on the left are player tokens. The automaton on the right is an npc. Does this help?

Sigh... I cut the screen on the right side too much. The blue token says 25ft while the yellow token pathing says 30ft /+5ft
EDIT: 
[Screencast from 2024-09-10 10-28-28.webm](https://github.com/user-attachments/assets/7b4f6f6e-3297-456f-ac28-2fa9a9e4151c) Here I redid it

**Comment by caewok** [comment]
Yes, that helps. In v0.10.11, the ruler will not count the invisible token.
