### ISSUE TITLE
Token can't be moved with click and drag

### ISSUE THREAD

**Issue by Commander-Fayne** [caewok/fvtt-elevation-ruler#203]
When I place a new token on the map, it can't be moved with the mouse. I can move it with the arrow keys, and I get this error

![image](https://github.com/user-attachments/assets/fa532f88-622d-4a27-be7a-54bb109da5d2)

**Comment by Commander-Fayne** [comment]
Here is the rest of the error

![image](https://github.com/user-attachments/assets/2eab5042-231c-4c28-ae24-9e715e732387)

I can't move any tokens at all.

**Comment by Commander-Fayne** [comment]
These errors pop up when I grab the token and try to move it. I can click and hold the token, and it follows my mouse, but when I let go, these errors show 

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(31, 31, 31); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(252, 235, 235); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:655" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">foundry.js:655</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Error thrown in hooked function 'refreshToken' for hook 'refreshToken'. Cannot read properties of undefined (reading '_extractAllMarkedPixelValuesAlongCanvasRay')
[Detected 1 package: terrainmapper(0.4.5)]
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Hooks.onError (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:654:24" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:654:24</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at 🎁call_wrapped [as call_wrapped] (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/lib-wrapper/src/lib/libWrapper-wrapper.js:507:22" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">libWrapper-wrapper.js:507:22</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at 🎁Hooks.onError#lib-wrapper (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/lib-wrapper/src/errors/listeners.js:140:11" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">listeners.js:140:11</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at 🎁Hooks.onError#0 (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/lib-wrapper/src/lib/libWrapper-wrapper.js:187:52" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">libWrapper-wrapper.js:187:52</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at #call (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:636:36" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:636:36</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Hooks.callAll (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:589:17" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:589:17</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Token5e.applyRenderFlags (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:26658:11" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:26658:11</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at #applyRenderFlags (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:26282:44" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:26282:44</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at mn.emit (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/packages/ticker/src/TickerListener.ts:71:47" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">TickerListener.ts:71:47</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Pt.update (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/packages/ticker/src/Ticker.ts:427:37" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">Ticker.ts:427:37</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Pt._tick (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/packages/ticker/src/Ticker.ts:129:22" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">Ticker.ts:129:22</button>)</span></span><div style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Caused by: TypeError: Cannot read properties of undefined (reading '_extractAllMarkedPixelValuesAlongCanvasRay')
[Detected 1 package: terrainmapper(0.4.5)]
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TileElevationHandler.holePositions (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/terrainmapper/scripts/TileElevationHandler.js:172:34" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">TileElevationHandler.js:172:34</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at #cutawayPolygonsHoles (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/terrainmapper/scripts/TileElevationHandler.js:375:32" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">TileElevationHandler.js:375:32</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at TileElevationHandler._cutaway (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/terrainmapper/scripts/TileElevationHandler.js:339:35" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">TileElevationHandler.js:339:35</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ElevationHandler._cutaway (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/terrainmapper/scripts/ElevationHandler.js:489:40" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">ElevationHandler.js:489:40</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at ElevationHandler.constructPath (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/terrainmapper/scripts/ElevationHandler.js:155:32" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">ElevationHandler.js:155:32</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.refreshToken [as fn] (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/modules/terrainmapper/scripts/Token.js:111:37" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">Token.js:111:37</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at #call (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:632:20" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:632:20</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Hooks.callAll (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:589:17" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:589:17</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Token5e.applyRenderFlags (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:26658:11" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:26658:11</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at #applyRenderFlags (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/scripts/foundry.js:26282:44" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">foundry.js:26282:44</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at mn.emit (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/packages/ticker/src/TickerListener.ts:71:47" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">TickerListener.ts:71:47</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Pt.update (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/packages/ticker/src/Ticker.ts:427:37" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">Ticker.ts:427:37</button>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Pt._tick (<button class="devtools-link text-button link-style" jslog="Link; context: script-location; track: click" role="link" tabindex="-1" title="https://foundry.gawdl3y.com/packages/ticker/src/Ticker.ts:129:22" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: unset; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;">Ticker.ts:129:22</button>)</span></div></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(31, 31, 31); font-family: monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(252, 235, 235); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: monospace; --source-code-font-size: 12px; --source-code-font-family: monospace; width: 469px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | onError | @ | foundry.js:655
-- | -- | -- | --
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:507
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:140
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:187
  | #call | @ | foundry.js:636
  | callAll | @ | foundry.js:589
  | applyRenderFlags | @ | foundry.js:26658
  | #applyRenderFlags | @ | foundry.js:26282
  | emit | @ | TickerListener.ts:71
  | update | @ | Ticker.ts:427
  | Pt._tick | @ | Ticker.ts:129
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133
  | requestAnimationFrame |   |  
  | Pt._tick | @ | Ticker.ts:133

</span></div>
</body>
</html>

Uncaught TypeError: Cannot read properties of undefined (reading '_extractAllMarkedPixelValuesAlongCanvasRay')
[Detected 3 packages: terrainmapper(0.4.5), elevationruler(0.10.10), lib-wrapper(1.12.15.0)]
    at TileElevationHandler.holePositions (TileElevationHandler.js:172:34)
    at #cutawayPolygonsHoles (TileElevationHandler.js:375:32)
    at TileElevationHandler._cutaway (TileElevationHandler.js:339:35)
    at ElevationHandler._cutaway (ElevationHandler.js:489:40)
    at ElevationHandler.constructPath (ElevationHandler.js:155:32)
    at TMPathForMovement (terrain_elevation.js:348:31)
    at TMElevationForMovement (terrain_elevation.js:332:10)
    at terrainElevationForMovement (terrain_elevation.js:282:15)
    at tokenElevationForMovement (terrain_elevation.js:234:10)
    at elevationFromWaypoint (terrain_elevation.js:195:30)
    at Ruler.destinationElevation (terrain_elevation.js:148:10)
    at elevateSegments (segments.js:143:22)
    at Ruler._getMeasurementSegments (Ruler.js:329:3)
    at 🎁CONFIG.Canvas.rulerClass.prototype._getMeasurementSegments#0 (libWrapper-wrapper.js:187:52)
    at Ruler.measure (foundry.js:36102:26)
    at Ruler._onMouseMove (foundry.js:36719:10)
    at Token5e._onDragLeftMove (Token.js:160:33)
    at 🎁CONFIG.Token.objectClass.prototype._onDragLeftMove#0 (libWrapper-wrapper.js:187:52)
    at MouseInteractionManager.callback (foundry.js:30834:17)
    at #handleDragMove (foundry.js:31213:26)
    at #handlePointerMove (foundry.js:31178:64)
    at vh.notifyListeners (EventBoundary.ts:1464:33)
    at vh.notifyTarget (EventBoundary.ts:658:14)
    at vh.propagate (EventBoundary.ts:310:18)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerMove (EventBoundary.ts:815:64)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerMove (EventSystem.ts:396:31)
holePositions @ TileElevationHandler.js:172
#cutawayPolygonsHoles @ TileElevationHandler.js:375
_cutaway @ TileElevationHandler.js:339
_cutaway @ ElevationHandler.js:489
constructPath @ ElevationHandler.js:155
TMPathForMovement @ terrain_elevation.js:348
TMElevationForMovement @ terrain_elevation.js:332
terrainElevationForMovement @ terrain_elevation.js:282
tokenElevationForMovement @ terrain_elevation.js:234
elevationFromWaypoint @ terrain_elevation.js:195
destinationElevation @ terrain_elevation.js:148
elevateSegments @ segments.js:143
_getMeasurementSegments @ Ruler.js:329
🎁CONFIG.Canvas.rulerClass.prototype._getMeasurementSegments#0 @ libWrapper-wrapper.js:187
measure @ foundry.js:36102
_onMouseMove @ foundry.js:36719
_onDragLeftMove @ Token.js:160
🎁CONFIG.Token.objectClass.prototype._onDragLeftMove#0 @ libWrapper-wrapper.js:187
callback @ foundry.js:30834
#handleDragMove @ foundry.js:31213
#handlePointerMove @ foundry.js:31178
notifyListeners @ EventBoundary.ts:1464
notifyTarget @ EventBoundary.ts:658
propagate @ EventBoundary.ts:310
dispatchEvent @ EventBoundary.ts:210
mapPointerMove @ EventBoundary.ts:815
mapEvent @ EventBoundary.ts:231
onPointerMove @ EventSystem.ts:396

**Comment by caewok** [comment]
That last group of errors can occur if you try to drag a token before Terrain Mapper is fully loaded. But they should stop appearing once it finishes loading. Do you see any errors further up in the console when it first loads the scene?

**Comment by Commander-Fayne** [comment]
After more testing, it's hit or miss. Sometimes Terrain Mapper finishes loading and the token can be dragged normally. Other times, Terrain Mapper seems to stall or time out and though it says it's finished loading, it hasn't, and I get those errors. Particularly, if I try to move the token before it's finished, I get those errors and it stalls out, and then no amount of waiting will help. It doesn't try to finish the load and tokens are stuck forever until I refresh the page. 

Last night, trying to run this map with my 5 players was just not working at all. We sat there for a good 5 minutes waiting for it to load with no one moving or touching anything and no matter what it just wouldn't load. 

For reference, this is a very complex map with 5 different stories of building, and 7 different tiles with Levels and Wall Height on all the layers and lots of Alpha space for Terrain Mapper to map out. It may be the server runs out of resources, or it may be my rig (I have a decent computer and we pay for very high end server space so those are unlikely but not zero chance,) but I thought I'd run this by you to see if maybe Terrain Mapper has an overflow or something inhibiting it from finishing loading a lot of layers in a timely manner.

**Comment by Commander-Fayne** [comment]
Additionally, I configured lib-wrapper to prioritize terrain mapper and elevation ruler, and that seemed to give me a better chance of Terrain Mapper finishing the map load.

**Comment by caewok** [comment]
Should be addressed in v0.10.11. You will also want to update Terrain Mapper to v0.4.6. I added some checks so TM would not error out if the workers don't finish. (They are only used for preparing to measure tiles with holes, so not super-critical.) I also made some performance improvements for when Elevation Ruler is measuring difficult terrain in a region.

Not sure if you can send me the map, but if you are able, that could be helpful. The scene json will give me the walls, but without the scene images and the tile images, it will only be of limited help.

**Comment by Commander-Fayne** [comment]
Unfortunately my session runs on Tuesdays so I've got prep to do. I can absolutely send you the map tomorrow if you want. Thanks so much for the quick turn around on this, came in just the nick of time.
