### ISSUE TITLE
5-10-5 (or alternating 1-2-1 as of v12) issue

### ISSUE THREAD

**Issue by SilvesTheRog** [caewok/fvtt-elevation-ruler#204]
Noticed a weird thing when moving a token with 25ft. speed diagonally using 5-10-5 rules.

When I move it diagonally left and up, the "tile" at 30ft. mark is colored green.
![image](https://github.com/user-attachments/assets/41e2f0ef-0284-463e-b419-0d979a956853)

But moving a token to any other diagonal direction shows me the yellow "tile" at the same mark, as it's supposed to
![image](https://github.com/user-attachments/assets/8e091f52-2b5a-4fec-beea-127c1ddfb379)
![image](https://github.com/user-attachments/assets/e2e28b08-a760-4878-96bf-93ff4b123408)

The same thing happens when speed is 40, 45, etc. And it's always in the same direction

**Comment by caewok** [comment]
Probably a rounding issue. Will look into it.

**Comment by caewok** [comment]
I think I fixed this in v0.10.11.
