### ISSUE TITLE
Players can't see the ruler when dragging tokens

### ISSUE THREAD

**Issue by SilvesTheRog** [caewok/fvtt-elevation-ruler#205]
As GM, i can see the rulers when i drag any tokens, but when players drag their owned tokens they don't see the ruler at all

Settings:

![Снимок экрана 2024-09-13 193534](https://github.com/user-attachments/assets/dcec2744-6ce6-4e0d-b697-df1ff28b8a20)
![Снимок экрана 2024-09-13 193541](https://github.com/user-attachments/assets/a6d849d6-c7df-45ef-9697-894a81f0c6a9)
![Снимок экрана 2024-09-13 193545](https://github.com/user-attachments/assets/b493c4b9-ee37-46a3-8e59-3d46bdea3808)

**Comment by caewok** [comment]
Are there any errors in the user's browser console? I am not seeing any issue with display of user tokens in v0.10.11.

**Comment by SilvesTheRog** [comment]
Hello!
Turns out, most of the settings like "Use token ruler" are client and every player had to set up elevation ruler themselves to make it work. Also requires pressing F5 to reload the page and apply the changes. I thought that changing the settings on the server would impact everyone. 

However, there's another issue. As a GM, I don't see the speed at all when someone is dragging a token. This happens to my players as well, they don't see my tokens' speed even though I didn't hide the ruler or hostile tokens speed from them:
![image](https://github.com/user-attachments/assets/e6c2d41a-c9fe-41a6-9d3a-bb46894d1729)
![image](https://github.com/user-attachments/assets/2e317bf3-3d14-40a3-949d-3a87156577a8)

**Comment by Quasxen** [comment]
Wanted to add some info on this during some personal testing. On the player side of things, the movement functions per the Core instructions. If they hold CTRL + Click and Drag, they will get the ruler. Then they can release both buttons and hit SPACEBAR when ready to move to the cursor. Waypoints are set with CTRL + Click. 

As the GM, you can just click and drag and right-click to set waypoints. Then SPACEBAR to move the path.

Also found that the setting for "Only allow Pathfinding in Explored Area" means the visual area. Fog of War areas will NOT pathfind

**Comment by caewok** [comment]
I think I found the underlying issue causing tiny ruler labels, so hopefully this is addressed in v0.10.16.
