### ISSUE TITLE
Not displaying (error) with starfinder system

### ISSUE THREAD

**Issue by ian612** [caewok/fvtt-elevation-ruler#206]
Using Starfinder 0.26.1, I can't get the ruler to display after the last update (it may also have something to do with a libWrapper update). I get this console error. This is on a fresh world with all modules disabled (except elevation ruler and libWrapper). I'm using the latest foundry version, v12.331.
![image](https://github.com/user-attachments/assets/bfde5171-fd1e-4b33-a790-fa958a886f07)

**Comment by caewok** [comment]
Should be addressed in v0.10.11. Thanks!
