### ISSUE TITLE
Players can see the drag ruler on hidden tokens

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-elevation-ruler#207]
Ideally hidden tokens wouldn't reveal their own movement.

**Comment by GambetTV** [comment]
To add to this, I don't mean when the Invisibility condition is placed on them. I mean when you've toggled their "Visibility State" to hidden.

Also, if I move a token on the other side of a wall a player can't see through, they can still see the movement, so it kind of ruins the surprise if I make little adjustments.

**Comment by DamianLyszczarczyk** [comment]
There is a toggle to hide the GM ruler altogether, that's what I am using right now

**Comment by caewok** [comment]
Fixed in v0.10.12. Thanks!
