### ISSUE TITLE
Incompatibility with Drag Ruler's movement history

### ISSUE THREAD

**Issue by Gawdl3y** [caewok/fvtt-elevation-ruler#21]
When using both Drag Ruler and Elevation Ruler together, Drag Ruler's movement history feature gets broken by Elevation Ruler. All movement history for tokens during combat display as being "NaN ft".

Drag Ruler without Elevation Ruler:
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/279900/362ea82c-5806-4578-8844-68553e874a18)

Drag Ruler with Elevation Ruler:
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/279900/6f0d0c9e-e04e-4e63-bb65-a902454437d3)

**Comment by caewok** [comment]
Unlikely to be fixed until this Drag Ruler [issue](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/310) is resolved.

But Elevation Ruler 0.7.4 adds options in settings to display the Foundry ruler when dragging tokens and to use different highlight colors based on token speed. I may be able to add movement history in a future update.

**Comment by caewok** [comment]
Closing; may revisit if Drag Ruler gets updated.
