### ISSUE TITLE
Conflict involving DAE, ER and Terrain Mapper

### ISSUE THREAD

**Issue by ctbritt** [caewok/fvtt-elevation-ruler#210]
Related to my other open issue (https://github.com/caewok/fvtt-elevation-ruler/issues/209), with the latest version of ER and DAE 11.3.64, a region with a difficult terrain set will not display any changes in the terrain. 

This is using the default difficult terrain that comes with terrain mapper. 
![CleanShot 2024-09-23 at 13 31 58](https://github.com/user-attachments/assets/94e6af66-89bb-40dc-ae9f-24430e83ac4c)

[This gif](https://share.cleanshot.com/Vh3cf39k) shows the issue. Dragging tokens over other tokens correctly adds +5 to their movement cost. This is reflected on the ruler. But when I drag the token through the difficult terrain territory. You can see this extra movement cost is not added. 

When DAE is disabled, the measured cost is factored in correctly: 
![CleanShot 2024-09-23 at 13 37 44](https://github.com/user-attachments/assets/669ed86a-1eb4-4332-939c-afee5dfb5dea)

There are no error messages in the console, however. 

Foundry 12.331
Dnd5e 3.3.1
ER: 0.10.11
DAE: 11.3.64

**Comment by caewok** [comment]
Setting aside the DAE issue, this should be addressed in v0.10.12.
