### ISSUE TITLE
PF2e not taking into account Move Speed

### ISSUE THREAD

**Issue by aburley1234** [caewok/fvtt-elevation-ruler#211]
The color highlighting is no longer occurring for the PF2e system. Colors all movement as red. I do notice that when using a gridless mode the highlighting appears at around 1 Foot, maybe something is being measured incorrectly?

PF2e Version: 6.4.1
Elevation Ruler Version: 0.10.11
libWrapper Version: 1.13.1.0

![image](https://github.com/user-attachments/assets/7512c089-dd40-4284-8296-8c6293999f53)

![image](https://github.com/user-attachments/assets/61e4057b-51a9-44c8-994c-50ad7197ff3e)

**Comment by digitalshadowhawk** [comment]
I'm glad someone else noticed this and I'm _not_ crazy. The only difference with my setup is that libwrapper is version1.13.2.0

**Comment by AngelofWoe** [comment]
I'm also seeing this issue. Until I updated to the recent update of libwrapper, pathfinding was breaking on walls entirely within the PF2e system. Even after updating to 1.13.2.0, movement speed isn't working in PF2e. I'm having to use 0.10.10.

**Comment by archhorde** [comment]
Also noticed this issue. Elevation ruler is version 0.10.11 and libwrapper is 1.13.2.0. Same symptoms as OP.

**Comment by caewok** [comment]
Addressed the speed coloring for pf2e in v0.10.12. Thanks! 

I don't know about pathfinding breaking, but there was an issue with a recent libwrapper version that has since been addressed by the libwrapper dev, so maybe you got the unlucky update?

**Comment by AngelofWoe** [comment]
> I don't know about pathfinding breaking, but there was an issue with a recent libwrapper version that has since been addressed by the libwrapper dev, so maybe you got the unlucky update?

Yeah, I'm pretty certain it was just a weird timing for me. I only brought it up just in case. The libwrapper update after fixed the pathfinding part.
