### ISSUE TITLE
[Feature Request] Only show one distance when there are no waypoints

### ISSUE THREAD

**Issue by nschoenwald** [caewok/fvtt-elevation-ruler#212]
Currently, two distance measurements are shown when dragging tokens. I guess one of them is the total distance for when using waypoints? My players and me rarely use waypoints so it would be better if the second measurement would only be shown after you have set your first waypoint.

![image](https://github.com/user-attachments/assets/393f89c0-570c-43c6-929b-509f7f82e2fc)

**Comment by caewok** [comment]
I addressed this for the "Customized Ruler Text" option, which was inadvertently displaying the default Foundry ruler label in some instances. But for the example you are showing, that is the default Foundry ruler behavior, so I don't intend to modify that. You can use the "Customized Ruler Text" if you want a cleaner ruler label. I also expect Foundry v13 to make substantial ruler changes, so you might want to submit a git issue to the Foundry VTT GitHub if you would like to see a cleaner default ruler label. Thanks!

**Comment by nschoenwald** [comment]
@caewok Thank you very much! Is there any documentation on what the "customized ruler text" option does? I couldn't find info in the readme.

**Comment by caewok** [comment]
Not really any documentation. But basically it uses a cleaner ruler label with more styled text and icons.
