### ISSUE TITLE
[seems to be GURPS specific] Total move bracket shows NaN for value 

### ISSUE THREAD

**Issue by Battenhatch** [caewok/fvtt-elevation-ruler#214]
Hi

I've been seeing this a while. In the GURPS system, ER shows the total move bracket as [NAN "unit"] (eg. [NaN m] in my case. I've tried it i clean worlds with GURPS Game Aid and Simple Worldbuilding, and maps otherwise the same, and this only shows under the GGA. Can anyone confirm/replicate/troubleshoot this?

edit: On Forge, all other elements latest version(s)

**Comment by caewok** [comment]
I added a PR to the GURPS git that should address this: 
https://github.com/crnormand/gurps/pull/1987
