### ISSUE TITLE
Conflict dealing with Terrain Mapper Difficult Terrain

### ISSUE THREAD

**Issue by DaGwann** [caewok/fvtt-elevation-ruler#215]
Hello. I'm having this problem where ER stops displaying the ruler when hovering over a region with the "Set Terrain" property from Terrain Mapper, making it difficult terrain. As seen in the video, the region correctly applies the effect when entering, and removes it when exiting the difficult terrain.

As a GM with the "Hide GM Token Ruler" setting active, I also stop seeing the ruler as a whole when I move the token after entering a region, needing to refresh Foundry to see it again. With a player or the option deactivated, this doesn't happen.

Gamemaster point of view:  
https://github.com/user-attachments/assets/51ecb212-6bed-4c0f-a391-1df979c66ff4

Player point of view:
https://github.com/user-attachments/assets/3080e42d-0a9a-490c-9d69-070bd3fb931d

Tested with no other modules active

Foundry v12.331
DnD v4.0.4
Elevation Ruler v0.10.13
Terrain Mapper v0.4.7
libWrapper v1.13.2.0

Thank you for the great work you do!

**Comment by a-mannered-bird** [comment]
I have the same issue on my side 👍

**Comment by ctbritt** [comment]
Having the same issue and documented thoroughly here: https://github.com/caewok/fvtt-elevation-ruler/issues/209

It's somehow related to DAE and particularly chokes on `attributes.system.ac.bonus | add | whatever value`.

**Comment by ctbritt** [comment]
I've been testing on dnd5e 3.3.1 however.

**Comment by caewok** [comment]
Addressed the error described in the OP in v0.10.16. Thanks!
