### ISSUE TITLE
Pathfinding seems broken for non GMs

### ISSUE THREAD

**Issue by ExileofBrokenSky** [caewok/fvtt-elevation-ruler#217]
As a GM, when I use pathfinding for tokens, it works, is fast and and good. However, if a player uses pathfinding, the browser hangs for about half a second anytime they drag a line that would need pathfinding, even if that's just slightly moving the line from a moment ago, thus chain hanging. It also fails to do any pathfinding, giving the classic you tried to move into a wall notification.

Using Current Versions of the module, it's dependencies, foundry and PF2e system as of posting date.

**Comment by caewok** [comment]
I am not seeing this issue. Can you copy a screenshot of the GM settings and the user settings into this chat?

**Comment by ExileofBrokenSky** [comment]
Sry I got lost in a busy week, I can't reproduce it now. Though I did have my players do some tests, and when it was happening, it was only to me when I was using forge's feature to log myself in as a player. My actual players didn't have this happen. So yeah, prolly a forge thing if anything.
