### ISSUE TITLE
No one can see ruler distances except the user making it

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-elevation-ruler#219]
When this module is active, if anyone (player or GM) drags a token, they can see the distance they move, but other users can only see the line, they can't see the numbers showing exactly how many feet are being moved.

Even stranger, this behavior seems to affect the normal ruler too, as in, not the token drag ruler, but just the normal ruler unconnected to tokens.

**Comment by caewok** [comment]
Should be fixed in v0.10.15. It affects the normal ruler because Elevation Ruler makes changes to the normal ruler.
