### ISSUE TITLE
[BUG] Incompatibility with Drag Ruler + Vision 5e

### ISSUE THREAD

**Issue by 9ryex5** [caewok/fvtt-elevation-ruler#22]
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/43207603/05fea504-2a48-46ca-aff7-ce4993e9e061)
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/43207603/c5d61988-29e4-40d8-8f55-127c7e8165c4)
When the moved token is outside from hearing range (default 30ft.) from one another everything is fine.
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/43207603/62fee5ca-804b-4db0-8d26-3eca7cf54346)
When the moved token is inside hearing range, drag/elevation ruler will not show and throw some errors
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/43207603/d5083021-4b1d-49a6-aa9e-f0bb0e2fc116)
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/43207603/bc44d6f4-572e-414a-9fef-fa49ab0d800f)
I'm not entirely sure which module is "causing" the problem, but since Drag Ruler plus Vision 5e work fine together and Vision 5e is not in the errors Elevation Ruler is probably the culprit.

**Comment by caewok** [comment]
Unlikely to be fixed until this Drag Ruler [issue](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/310) is resolved.

But Elevation Ruler 0.7.4 adds options in settings to display the Foundry ruler when dragging tokens and to use different highlight colors based on token speed. 

I will keep this open to see if I can address compatibility with Vision 5e.
