### ISSUE TITLE
in gridless scenes, it displays terrain penalty after placing a waypoint

### ISSUE THREAD

**Issue by JosephA1997** [caewok/fvtt-elevation-ruler#220]
![Screenshot 2024-10-13 140005](https://github.com/user-attachments/assets/bc2f075e-050f-4bda-81f1-9714d3aaad63)

after placing a waypoint, it diaplays the terrain penalty icon and no longer updates the total movement calculation

**Comment by MeatMarionnette** [comment]
Same here

**Comment by n0q** [comment]
Probably a duplicate of #218.

**Comment by JosephA1997** [comment]
yeah i did see that one, but they specified that it only happened when certain module settings were enabled. this is happening in gridless scenes regardless of module settings

**Comment by Xjph** [comment]
This appears to also happen with automatic waypoints from pathfinding.

Moving around corner, gridless.
![image](https://github.com/user-attachments/assets/da99b2eb-0aa0-4ad3-b6f4-92c714796f4b)

Moving into same area with no pathfinding necessary.
![image](https://github.com/user-attachments/assets/a32d746d-f0cc-4a81-91a0-e4080c57124e)

Moving around corner with grid.
![image](https://github.com/user-attachments/assets/597f97df-f37a-4790-8c94-7a1bb5cb6373)

**Comment by caewok** [comment]
Should be addressed in v0.10.15. Thanks!
