### ISSUE TITLE
Pathfinding is not working with theripper93's Wall Height 6.1.0

### ISSUE THREAD

**Issue by molo4evan** [caewok/fvtt-elevation-ruler#223]
In Wall Height 6.1.0 (created by theripper93, required for Levels module) was removed Vaulting setting (AFAIU, is is enabled by default now).

It leads to error on walls intersection during token dragging when pathfinding is enabled, because in WallTracer.js:386 your code tries to access the setting, which no longer exists.

Please consider to update your code to support the latest version of Wall Height or make this module integration optional.

**Comment by caewok** [comment]
Fixed in v0.10.15. Pathfinding will assume vaulting is enabled if Wall Height is active.
