### ISSUE TITLE
[Bug] Tokens can be moved through walls

### ISSUE THREAD

**Issue by STBaf** [caewok/fvtt-elevation-ruler#224]
If a user controls multiple tokens and select more then one token, you can move the selected tokens simultanously.
When you position 2 tokens in the right distance to a wall (one nearer and one further away), select both and then drag the token that is farer away from the wall closer to the wall, the other token will be moved, too, and pushed through a movement restricting wall.
Collision detection seem to fail for the token that is moved alongside the dragged token. This only happens when draging the tokens with the mouse. If you move tokens by cursors keys fieldwise the additional moving token stops correctly at the wall, collision detection seem to work in that case.
This seem to be system independent.

Steps to reproduce:
1. Create a fresh world with any system (I tried the latest PF2 system and the latest DnD5e 3.x) and enable Elevation ruler (+ dependency libwrapper)
2. Create a unpriviliged player account additional to Gamemaster
3. Create a test scene with a wall, create 2 Actors, grant ownership to both actors for the unpriviliged player account, place tokens for actors on scene
4. place tokens in front of wall, for example one 2 grid fields away and the other 5 grid fields away
5. let the unpriviliged player account select both tokens, move the token that is 5 grid fields away with the mouse behind the wall or close enought to the wall that the nearer token would move far enough that it should end behind wall if it moves same amount of grid fields
6. Dragged Token will move to wall and stop with collision detection. Other token (original 2 fields away) duplicates the movement and passes beneath the wall.
7. Repeat the same and move with keyboard instead, both tokens stop when reaching the wall
8. Repeat with disabled elevation ruler, only core. Both tokens will stop on wall with collision detection, even with dragging with mouse.

Tested on: Foundry 12.311, Dnd5e 3.3.1 / PF2 6.5.1, only Elevation Ruler 0.10.14 (+ libwrapper) active (or no modules active for test if reproducable without Elevation ruler)

**Comment by caewok** [comment]
Clever. Fixed in v0.10.15.
