### ISSUE TITLE
incompatibility with drag ruler 

### ISSUE THREAD

**Issue by Orionox** [caewok/fvtt-elevation-ruler#24]
When both modules are active drag ruler stope showing the graphic when a sprite is moved additionally, an error is commonly through about elevation needing to be a finite number

**Comment by caewok** [comment]
Unlikely to be fixed until this Drag Ruler [issue](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/310) is resolved.

But Elevation Ruler 0.7.4 adds options in settings to display the Foundry ruler when dragging tokens and to use different highlight colors based on token speed.
