### ISSUE TITLE
patching.js throwing not found when calling Ruler.js

### ISSUE THREAD

**Issue by lucasmiranda2711** [caewok/fvtt-elevation-ruler#25]
I guess the print says it all, while trying to import the Ruler.js it't throwing a 404, when calling /modules/elevationruler/scripts/ruler.js it seems to work, maybe it's case sensitive?

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/19212106/dceece7f-6253-4117-8604-c03218003f42)

**Comment by caewok** [comment]
Should be fixed in 0.7.5. And yes, it is case sensitive in some systems (usually Linux).
