### ISSUE TITLE
Module throws 404 when loading resource ruler.js

### ISSUE THREAD

**Issue by lucasmiranda2711** [caewok/fvtt-elevation-ruler#26]
Sorry to be annoying but I think it has to do with the renaming to fix [#25](https://github.com/caewok/fvtt-elevation-ruler/issues/25)
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/19212106/68e69f6f-68d2-4ac8-a497-d430c628113e)

I think this line should be altered too:

https://github.com/caewok/fvtt-elevation-ruler/blob/7ac6276963e4490a4c397fc9ff0342d1bea6103e/scripts/module.js#L13

**Comment by caewok** [comment]
Damn, missed that one!

**Comment by caewok** [comment]
Okay, let's see if v0.7.6 does the trick!
