### ISSUE TITLE
Feature: Token movement type

### ISSUE THREAD

**Issue by caewok** [caewok/fvtt-elevation-ruler#33]
https://ptb.discord.com/channels/915186263609454632/1193755370607345695/1194950663889756240

Add something like the UX from [Elevation Drag Ruler](https://github.com/PepijnMC/ElevationDragRuler) to allow type of token movement to be selected.

**Comment by ravingdragoon** [comment]
This would be an amazing addition to this great tool!

**Comment by caewok** [comment]
Added in v0.8.3.
