### ISSUE TITLE
[BUG] Color doesn't change beyond dash range

### ISSUE THREAD

**Issue by GhostwheelX** [caewok/fvtt-elevation-ruler#35]
As the title suggests, the color doesn't change when dragging creatures beyond their normal range.

Picture added for clarity.

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/68725723/7c049c0b-787f-4047-8e96-b460e616d5a6)

**Comment by caewok** [comment]
Hopefully fixed in v0.8.2. Please let me know if it is not.
