### ISSUE TITLE
[Feature Request] Allow right-click to be used to set waypoints

### ISSUE THREAD

**Issue by GhostwheelX** [caewok/fvtt-elevation-ruler#36]
Would it be possible to allow user to set movement waypoints by right-clicking?

**Comment by caewok** [comment]
You can using the ruler. You cannot when dragging a token. That is because I could not get Foundry to pass through the right-click to the ruler when dragging.

**Comment by GhostwheelX** [comment]
Drag Ruler has an option for it, would it be possible to take inspiration from how that module does it?

**Comment by caewok** [comment]
It's possible. I think Drag Ruler is intercepting the `Token.prototype._onDragLeftCancel` method. Looks like I might be able to see a control-click or right-click there. I will look into it.

**Comment by caewok** [comment]
Not quite there yet. I got the right-click to work to add a waypoint, but it results in the token preview staying on the scene after the move until you switch control layers. Have not yet figured out why or how to prevent that.

**Comment by caewok** [comment]
Added in v0.9.5.
