### ISSUE TITLE
[Feature Request] Hide GM ruler

### ISSUE THREAD

**Issue by LukasPrism** [caewok/fvtt-elevation-ruler#42]
Just popping this here in case you missed it on discord.

Please consider hiding the GM ruler if it’s not within the player’s field of vision. Currently it’s visible behind walls etc so players can meta game and see where enemies have retreated to, that kind of thing.

Many thanks for a wonderful module!

**Comment by caewok** [comment]
Do you already know that you can turn off the GM ruler display to users by going to the GameSettings:User Management:Configure Permissions?

Are you asking to further hide or display the GM ruler beyond that?

**Comment by LukasPrism** [comment]
Nope this can be closed… sorry about that. I guess I’ve been using Drag Ruler since day one I’ve never even looked at that setting. Thanks heaps.
