### ISSUE TITLE
Uncaught TypeError : Cannot read properties of undefined (reading 'contains')

### ISSUE THREAD

**Issue by lineatterobin** [caewok/fvtt-elevation-ruler#43]
Hi,

Since 0.8.3, i get an error when using the ruler. (The ruler doesn't appear by the way)
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/9580241/96afe928-5ff3-4408-a53c-b696cf8bf71b)

I'm using Pathfinder 2e system 513.4 and i have no other active module using the ruler.

Regards.

**Comment by caewok** [comment]
I think this is fixed in v0.8.5.
