### ISSUE TITLE
Measure Distance Tool fails to work with Elevation Ruler on any scene when Elevated Vision is active, or on gridded scenes when Terrain Mapper is active

### ISSUE THREAD

**Issue by daevadragon** [caewok/fvtt-elevation-ruler#51]
Hey there, not sure if this is a feature request or a fix, I'm wondering if there's any way you can or plan to resolve this. Right now it looks like Measure Distance must be drawn from an owned token while Elevation Ruler is active, which is a limit to the functionality of the tool for me and my players that we'd prefer not to have. We primarily use the token ruler functionality of elevation ruler to measure from tokens, especially since we have Hover Distance measuring distances between owned/controlled tokens and their targets, and would really love to see the Measure Distance tool as a more general use function,.

**Comment by daevadragon** [comment]
It seems this is a conflict with Elevated Vision, if I only have Elevated Vision and Elevation Ruler active, the measure distance tool fails to work at all. It also seems I have another module that interferes with Elevation Ruler and the Measure Distance tool on gridded scenes, will comment again when I've determined which module(s) that might be.

**Comment by daevadragon** [comment]
The module preventing the Measure Distance tool from working with Elevation Ruler on gridded scenes is Terrain Mapper.

Edit: Actually looks like Measure Distance, Elevation Ruler, and Terrain Mapper work fine together when those are the only two active modules. Likely a third interacting here, will continue troubleshooting to find potential culprit if/when this issue can start to be addressed.

**Comment by caewok** [comment]
Should be fixed in v0.8.9. One of these issues was with Terrain Mapper, so I released a small update to TM to fix that as well. Thanks!
