### ISSUE TITLE
Tokens locked to movement speed

### ISSUE THREAD

**Issue by ravingdragoon** [caewok/fvtt-elevation-ruler#52]
Not sure if this is a bug or enhancement request. The tokens, on DnD 5e at least, are currently locked to their base movement speed, which means to dash they have to move the base speed, stop, then move the base speed again. Also, as GM I am not able to simply move the tokens where I want on a map, I am locked to moving them a few spaces at a time. If this is the intended functionality, would it be possible to get some sort of override toggle or GM override setting?

**Comment by caewok** [comment]
What version of dnd5e are you using?

**Comment by ravingdragoon** [comment]
3.0.3

**Comment by caewok** [comment]
I took a look and cannot replicate this. If you drag the token, it moves the token as expected through the whole movement.

 If you use the ruler and spacebar, it also moves the token as expected. But I do see that if you use the ruler to move, it is possible to stop the movemnet early by releasing the mouse before the movement finishes. So I will look into what is causing that. I also noticed that it is throwing an error when both Elevated Vision and Terrain Mapper is active and you move through a terrain.

**Comment by ravingdragoon** [comment]
So, it seems to work better now, but it still doesn't seem ideal for a GM moving groups of tokens. It now drags tokens to the first end point of their movement, then the end point of their dash, then to the final end point. Is this as intended? If so, is there a way to just have the tokens move to the final destination instead?

**Comment by caewok** [comment]
In order to convince Foundry's Ruler to change highlighting based on speed, I need to add the waypoints. And Foundry's ruler moves tokens between waypoints. So no, I don't think the tokens can just move to their final destination.
