### ISSUE TITLE
Token ruler not measuring 5-10-5 correctly

### ISSUE THREAD

**Issue by GravityBlade** [caewok/fvtt-elevation-ruler#56]
When using the built in Measure Distance ruler, the Pathfinder-based movement of 5-10-5 is not being correctly. It's using 5-10-10 instead.
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/101123954/7dca3897-444e-46e1-9d1d-d8a97ad77d34)

When the module is removed the measured distance is correct.

**Comment by caewok** [comment]
I think this should work in v0.8.10 but please let me know if it does not.
