### ISSUE TITLE
Waypoints for pathfinding not in grid center resulting in weird paths 

### ISSUE THREAD

**Issue by si-lang** [caewok/fvtt-elevation-ruler#57]
### Setup:
Foundry: v11 Build 315
System: Pathfinder 1e 9.6
Module: v0.8.9
Relevant Settings: Terrain Grid Measurement: Center Point

### Description:
When using the Elevation Ruler with pathfinding enabled, waypoints are calculated not in the center of some grids, leading to weird and/or incorrect paths (sometimes even moving through walls).

### Example:
![Setup](https://github.com/caewok/fvtt-elevation-ruler/assets/9452669/b72fc74d-525a-4d20-aadf-0a148daf4db2)
![Movement](https://github.com/caewok/fvtt-elevation-ruler/assets/9452669/9415b9bf-fe3b-42a1-8d9b-7904f8e0fb80)

**Comment by caewok** [comment]
Should be mostly fixed in v0.8.10. I wouldn't say it will always put the waypoint in the center of a grid, but it should not allow movement through walls and the paths should be much less weird thanks to more aggressive path straightening.
