### ISSUE TITLE
[Feature Request] Allow configuration of distance increments

### ISSUE THREAD

**Issue by si-lang** [caewok/fvtt-elevation-ruler#58]
It would be great to be able to specify when and how color coding of a measured path applies. - This feature would be relevant for systems, that allow more than two times the base movement per round (e.g. Pathfinder 1 with Unchained Action Economy or Warhammer 4e - Run Action for sprinting).

I could imagine having a list of range increments, supporting constant values and formulas referencing actor properites (such as base movement). - This feature would make this module applicable to a very broad range of systems and system variants.

**Comment by caewok** [comment]
Added to `CONFIG.elevationruler.SPEED` in v0.8.10. You can now add an unlimited number of speed categories in the config, as well as custom speed functions if necessary.

If you have a specific system(s) in mind, feel free to open a Git issue describing how speed for that system should work. I can add it to the defaults.
