### ISSUE TITLE
Feature request: compute token height with terrain height

### ISSUE THREAD

**Issue by HenriDeh** [caewok/fvtt-elevation-ruler#6]
Hi, 

I think this mod would be more complete if it could couple token and terrain elevation. I'm speaking here only with regards to the ETL module complementarity. 

When a target token is on an elevated terrain and a player wants to see if it has range to shoot it, the player will use a ruler from his token to the target token. But the ruler will use the token's elevation to calculate the distance regardless of the terrain elevation. Which forces the GM to set the token's elevation to that of the terrain it currently is on. 

I think this module should allow to consider the elevation of a token as that of the terrain when the elevation is 0, or consider the elevation of the token as the maximum between the terrain elevation (max elevation) and the token's elevation. The latter option allows to use flight above elevated places. 

Thanks for the useful mod though.

**Comment by caewok** [comment]
It is not clear to me why the target token in your example is not already at the elevation of the terrain. I would think that a good default is to assume that when a ruler hovers over a token, you want to measure to that token. Maybe I am missing something, but it seems like the options here are:

Assume elevation 20 for the terrain.

1. Token --> target token at elevation 30. Elevation Ruler uses the target token elevation of 30. Target is assumed to be hovering or flying.
2. Token --> target token at elevation 0. Elevation Ruler uses the target token elevation of 0. Target is assumed to be burrowing.
3. Token --> target token "on the ground" at elevation 20. Doesn't matter which elevation is used. 

I could see how it might be useful to have a key command to alternate between tokens in the same space and the terrain. But my players can barely remember how to work the ruler; I am not sure anyone would actually use that. 

Beyond that, it sounds like what you want is to have the target token have its elevation automatically adjusted when on elevated terrain. Some mods can do that, including [Elevated Vision](https://github.com/caewok/fvtt-elevated-vision)
