### ISSUE TITLE
During combat after the first move the colors are incorrect

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-elevation-ruler#62]
If you have tracking on for combat and you have colored trails based on movement rate, it tracks your movement for the first move each turn during combat. If you move a second time, the trail is just green no matter how far you move.

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/12570777/4551b71b-e710-4b83-bf48-efaad3a6ffc6)
![image](https://github.com/caewok/fvtt-elevation-ruler/assets/12570777/dcc8c3b6-ab43-4452-ad01-891ca8e4351f)

**Comment by caewok** [comment]
Fixed in v0.8.11. Thanks!
