### ISSUE TITLE
[Feature Request] Better grid movement for small or tiny creatures

### ISSUE THREAD

**Issue by NdranC** [caewok/fvtt-elevation-ruler#70]
As of right now, I'm having a hard time getting small or tiny creatures being on the right quadrant of a single square grid. Occasionally I seem to be able to shimmy it over but it's inconsistent to do compared to the unmodded behavior.

**Comment by GhostwheelX** [comment]
I'm having the same issue, tiny creatures tend to go into the top-left quadrant of a given square, rather than any of the other quadrants within the square.

**Comment by caewok** [comment]
Version v0.9.4 makes some improvements to dragging. Tiny creatures are still a bit weird, though. Right now, they tend to default to the center of the square, where they work well. If you hold "shift" to unsnap them, things can still get a bit weird after that. Will revisit.

**Comment by caewok** [comment]
Fixed in v0.9.5
