### ISSUE TITLE
Adding a option for metric system 

### ISSUE THREAD

**Issue by atomikafka** [caewok/fvtt-elevation-ruler#72]
To add option for metric measurement system, movements being shown in meter instead of foot. As rule of thumb 2 mts=5ft would be  perfect length.

**Comment by caewok** [comment]
You can do this already. Go to the scene configuration and change the grid scale units to whatever you want.

<img width="556" alt="Screenshot 2024-06-01 at 9 44 37 AM" src="https://github.com/caewok/fvtt-elevation-ruler/assets/1267134/8120602a-8290-4227-ad59-57788d2ced26">
