### ISSUE TITLE
[feature request] Add 'use pathfinding' in settings or default as on

### ISSUE THREAD

**Issue by morgan613** [caewok/fvtt-elevation-ruler#73]
Small thing: I think it would be nice to add 'use pathfinding' in settings so that as GM I can set it as on for players (via other modules that let me influence player settings). 

Alternatively, setting 'use pathfinder' to default as on works for me. It is an amazing feature and I think most people prefer it on but for new users the toggle is easy to miss (at least in my experience).

**Comment by caewok** [comment]
I switched the default to enabled for pathfinding in v0.9.4. I am a bit loathe to add more settings, but will consider it. Thanks!

**Comment by morgan613** [comment]
That's fair about not wanting to add more settings! Pathfinding being defaulted as on is sufficient for my purposes, thank you so much!
