### ISSUE TITLE
[Feature Request] WASD Keys and dragging

### ISSUE THREAD

**Issue by Bryn1701** [caewok/fvtt-elevation-ruler#74]
Hi there. It looks like an amazing module. I have been using Drag Ruler for the last few years but it looks like this will be my new default.

I was curious if it would be possible to have both WASD and Drag keep track of movement? For instance if you move 10 feet with drag, then have to use WASD to move 2 squares of 5 feet, when I go to pick the token up to drag it further it would have combined the drag movement of 10 feet and the WASD movement of 10 feet?

More and more modules are using WASD to get around smaller corridors and through doors and onto teleports and scene regions now, it would be great to have both modes of movements combined. 

Thanks in advance
Bryn

**Comment by caewok** [comment]
This used to work but a change in v12 created a bug. I think I have resolved that in v0.9.4 and WASD should now count towards the movement if they are in combat.
