### ISSUE TITLE
[Documentation Request/Suggestion] Highlight the token drag ruler/pathfinding aspect

### ISSUE THREAD

**Issue by morgan613** [caewok/fvtt-elevation-ruler#75]
The short description of the module is currently:

"Modify Foundry VTT ruler to adjust for relative elevation of the destination."

But I think this module is more than that! Drag Ruler is the 6th most installed module [https://foundryvtt.com/article/year-in-review-2024/#modules-usage](url) but this module does that and more! 

I think a fair amount of users might be more interested in the drag ruler aspect. But regardless, I think it is worth highlight some of the other capabilities more prominently (e.g., in the description of the module or even in the module name).

**Comment by morgan613** [comment]
Oh also, the readme still mentions pathfinding as broken, so maybe worth removing that

**Comment by caewok** [comment]
Thanks for that feedback. I improved the description on the git page, added some webm videos, and improved the description on the Foundry page. Hopefully that helps!

**Comment by morgan613** [comment]
Looks great! Thank you for all your hard work!
