### ISSUE TITLE
Support for custom speed providers and colors

### ISSUE THREAD

**Issue by Vixiea** [caewok/fvtt-elevation-ruler#77]
If possible, please allow a user to specify the path to the actor's speed attribute along with the colors used through the GUI. Elevation Ruler doesn't recognize the Lancer system's speed attribute. Additionally, Lancer has conditions, like Slowed, that allows the full use of normal movement but prevents the use of "boosting" (dash). A method of handling these cases similar to the Lancer Speed Provider module would be appreciated.

**Comment by caewok** [comment]
Technically, you can set custom speeds already, by modifying `CONFIG.elevationruler.SPEED.` See the instructions on the [main page](https://github.com/caewok/fvtt-elevation-ruler#setting-speed-colors). For things like conditions, you can define `SPEED.maximumCategoryDistance` to be a function that handles that. You can do that in a world script or a module that you could share with others. 

See [PF2e Elevation Ruler](https://github.com/7H3LaughingMan/pf2e-elevation-ruler/tree/main) for a good example of this.
