### ISSUE TITLE
Movement calculation issues with Hexes

### ISSUE THREAD

**Issue by Vixiea** [caewok/fvtt-elevation-ruler#78]
When playing on a Hexagonal Row - Odd grid, attempting to move to the top left or bottom left hexes costs 1.5 while all other hexes cost 1.
![Hex Ruler Error](https://github.com/caewok/fvtt-elevation-ruler/assets/70721547/ac3a6d94-8c0f-4415-93b6-7d1d8324be10)

**Comment by caewok** [comment]
Should be addressed with the measurement changes in v0.10.2.
