### ISSUE TITLE
[Feature Request] Pathfinder 2e Support

### ISSUE THREAD

**Issue by Vaizt** [caewok/fvtt-elevation-ruler#79]
It would be nice to see support for this system that is continuing to grow in popularity. However, I'm not entirely sure how this would interact with the different movement speeds tokens can have.

**Comment by sirkerry** [comment]
Yes, PF2e support would be awesome.

**Comment by mortiferus93** [comment]
Oh yeah, since Drag Ruler won't be updated anymore, PF2e support would be great!

**Comment by apoapostolov** [comment]
I would start/extend a small 30$  bounty for the dev who implements a proper PF2 support with color for 1x 2x 3x 4x and beyond movement, similar to Drag Ruler.

**Comment by NdranC** [comment]
Using it in pf2e at the moment. It's usable so far. The one thing is missing is that for some reason it's not rounding down to the closest 5ft at all. I keep getting 12.5 ft measurements and others.

**Comment by mortiferus93** [comment]
> Using it in pf2e at the moment. It's usable so far. The one thing is missing is that for some reason it's not rounding down to the closest 5ft at all. I keep getting 12.5 ft measurements and others.

The colour indications for the distance moved are also not working, i.e. one colour for the first movement action, another colour for the second movement action and so on

**Comment by 7H3LaughingMan** [comment]
I am not sure if something like this would truly be added to Elevation Ruler, but I did create a simple module the extend Elevation Ruler with support for PF2e. It uses the Elevation Ruler API to get a token's regular speed, burrow speed, and fly speed based on the movement type. Also adds different coloring for single action, double action, triple action, and quadruple action strides.

https://github.com/7H3LaughingMan/pf2e-elevation-ruler

**Comment by NdranC** [comment]
Thank you for the new module. I noticed it's only v12 support. Would it be ok to add v11 support to it as well? Many of the other pf2e modules I use are still not fully ported and might not be for a while.

**Comment by Symon-S** [comment]
@NdranC Drag ruler still works for pf2e v11, so you could just use that for v11.

**Comment by caewok** [comment]
Thanks @7H3LaughingMan for the module. @apoapostolov Does that do what you were looking for? 

I am inclined to leave PF2e Elevation Ruler as a separate module. I think it will serve as a good template for other systems that may have complicated movement rules. Maintaining a bunch of complex system rules within Elevation Ruler is something I would prefer not to do. I am reasonably content with the current API in Elevation Ruler for defining speeds, but please let me know if it is lacking some key feature.
