### ISSUE TITLE
[Feature Request] Right Click to Add Waypoint

### ISSUE THREAD

**Issue by GambetTV** [caewok/fvtt-elevation-ruler#80]
Creating waypoints is super useful, but I find it kind of unintuitive to use the keyboard to create them. I feel like Right Click is much more intuitive, but unfortunately because Foundry does not let you add mouse buttons to the "Configure Controls" settings, it is not possible for us to add this ourselves. I wonder if you'd be able to add a setting to your module that adds this behavior, if not by default, then at least as a toggleable setting, similar to what "Drag Ruler" did.

**Comment by caewok** [comment]
Added in v0.9.5. I also split out the token ruler and regular ruler waypoint keybindings, to give you more options. FYI, I rather like setting "meta" for adding and "control" for removing waypoints. Depends on your keyboard/mouse setup, I suppose.
