### ISSUE TITLE
[Request] Add option to disable elevation shange display if no elevation change is present

### ISSUE THREAD

**Issue by nschoenwald** [caewok/fvtt-elevation-ruler#81]
A lot of my scenes are flat and I don't need the display of the 0 elevation change on my ruler or when dragging tokens then. An option to only show the elevation change if it is greater than 0 would be perfect.

**Comment by GregoryWarn** [comment]
My players asked me the same request

**Comment by caewok** [comment]
Added in v0.9.10.
