### ISSUE TITLE
Movement track during combat resets current 5-10-5 interval after drag

### ISSUE THREAD

**Issue by Mystler** [caewok/fvtt-elevation-ruler#87]
It appears that in a system with 5-10-5 measuring rules for diagonals, Elevation Ruler resets the step interval at the end of every drag during the same tracked movement action.

As an example, if a token has 20ft speed and moves 20 feet diagonally, if it is in one drag it does track it properly as 3 squares (5-15-20). However, if a player does not use the waypoint keybind and instead moves manually multiple times during the same "action" it will start with the 5 increment every time, so for the same 20 ft speed a player will be shows 4 successive diagonal moves as 20 ft - 5 every time.

Ideally, the interval if the track setting is on should not be reset at the end of each drag but only for squares that go from one action interval into the next.

(My use case is the PF2E system, using the module that adds basic support for Elevation ruler. I still think this is the place to put the issue up but let me know if I'm wrong.)

**Comment by caewok** [comment]
In v0.9.11, it now tracks the number of diagonals during combat move(s) in a turn. That should resolve the situation you described where a player could break up the movement during combat and get a different move result. 

I did not add anything to reset the diagonal count within the turn. [Pf2e](https://2e.aonprd.com/Rules.aspx?ID=2356) rules say that you count diagonals for all movement during a turn. Same for dnd5e, I believe. So it wouldn't make sense to reset the diagonal count within a given turn.
