### ISSUE TITLE
[Feature Request] A way to reset movement history

### ISSUE THREAD

**Issue by TombstoneTT** [caewok/fvtt-elevation-ruler#89]
Love being able to keep track of movement history, especially in combat, but sometimes mistakes can happen, so it'd be nice to have a way to reset the current movement history in a round.

**Comment by 117ksk** [comment]
+1

**Comment by L4D15** [comment]
+1

It's very common for my players to move, then realize that's not what they really wanted to do and go back to the starting position, but the distance moved is still counting. It would be nice to have a button or something to reset the distance counted that round.

**Comment by Dddsasul** [comment]
+1 using the normal ctrl+z that already moves the character back should also undo the last movement addition

**Comment by Geektasticdad** [comment]
> Love being able to keep track of movement history, especially in combat, but sometimes mistakes can happen, so it'd be nice to have a way to reset the current movement history in a round.

You can do this in the combat tracker, just right click the character and there's an option to reset movement history.

**Comment by Dddsasul** [comment]
> You can do this in the combat tracker, just right click the character and there's an option to reset movement history.

I don't see that button, I am very confused.

**Comment by Geektasticdad** [comment]
> > You can do this in the combat tracker, just right click the character and there's an option to reset movement history.
> 
> I don't see that button, I am very confused.

Ugh, I'm a dork, that was a feature of Drag Ruler (which doesn't work in v12). Yes, I agree this would be a great feature to add to Elevation Ruler.

**Comment by caewok** [comment]
Added in v0.9.9. Note that ctrl-z to undo movement during combat should now also change back the movement history. 

The button in the combat tracker allows the GM to reset the current combantant such that its movement for the current combat round is 0. 

If a user hits ctrl-z after moving a token, the token will be returned to its previous position and its movement history should be as though that last move was never made. I believe Foundry lets you step back 10 undos total at the moment.
