### ISSUE TITLE
[BUG] Error when elevating a token

### ISSUE THREAD

**Issue by Kharmans** [caewok/fvtt-elevation-ruler#92]
When change an elevation with `[` or `]` buttons, the elevation don't change and this error is showed.

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/112586547/4cd6b1af-abb1-44ec-8ad0-919fb88f7608)

**Foundry**: v12
**D&D5e**: v3.2.1
**Elevation Ruler**: v0.9.4

**Comment by Geodragon9** [comment]
I am seeing the same with Pathfinder 2e. Also version 0.9.4

**Comment by caewok** [comment]
Should be addressed in v0.9.5.
