### ISSUE TITLE
 [Translation] Add Polish translate

### ISSUE THREAD

**Issue by Lioheart** [caewok/fvtt-elevation-ruler#94]
Below I add Polish translate.

**Comment by caewok** [comment]
That looks like a file for a different module.

**Comment by Lioheart** [comment]
Wait a second... I made a mistake!

Below is correct file. Sorry one again.
[pl.json](https://github.com/user-attachments/files/15943308/pl.json)

**Comment by caewok** [comment]
Thanks! Added in v0.9.5.
