### ISSUE TITLE
[Feature Request] Support for tokens smaller than one grid square

### ISSUE THREAD

**Issue by filipemmesquita** [caewok/fvtt-elevation-ruler#95]
currently, token ruler only properly works on tokens that are smaller than one grid square when they are in the center of the square. It also doesn't allow such tokens to move to other positions within the square.
DnD and Pathfinder both have some creatures that are tiny and can occupy the same square as other creatures. being able to put them on different corners of the same square is incredibly helpful.

**Comment by ChasarooniZ** [comment]
Screenshot showing the issue with the ruler for this use case now

![image](https://github.com/caewok/fvtt-elevation-ruler/assets/79132112/8af43015-12e8-435c-9b75-5778463ddcf7)

**Comment by caewok** [comment]
Fixed in v0.9.5
