### ISSUE TITLE
[Translation] RU 

### ISSUE THREAD

**Issue by VirusNik21** [caewok/fvtt-elevation-ruler#96]
Hello.
I made a Russian translation of your module. Could you include it in the next version of your module?
[ru.json](https://github.com/user-attachments/files/15875908/ru.json)

**Comment by VirusNik21** [comment]
[ru.json](https://github.com/user-attachments/files/15960312/ru.json)
File with RU Translate

**Comment by caewok** [comment]
Thanks! Added in v0.9.5.
