### ISSUE TITLE
[Bug] Waypoints cause movement to be counted again for the Track Combat Move value in Pathfinder 2e

### ISSUE THREAD

**Issue by SoupcanAnthill** [caewok/fvtt-elevation-ruler#98]
Using Pathfinder 2e 6.0.3, Foundry 12.327, and Elevation Ruler 0.9.4. Tested in a new world with no other modules.

When adding a waypoint during movement in combat, once the movement is finished the "Prior:" value adds the previous movement's value again for each waypoint set.

For example, moving 15 feet, adding a waypoint, and moving another 15 feet, it should read 30 ft. Instead, it reads 60. Moving 10 feet, waypoint, 10 more feet, second waypoint, 10 more feet causes it to read 90 instead of 30. Moving 30 feet and setting 6 waypoints causes it to read 180 ft.

**Comment by Risca** [comment]
Looks like it's not only waypoints. Simple moving a character (and releasing the button) seem to double the "Prior" value.

Foundry 12.327
Pathfinder 2e 6.0.4
Elevation ruler 0.9.5
PF2e Elevation Ruler 12.327.3

I haven't verified if this is only related to the "PF2e Elevation Ruler" integration plugin or if it affects "Elevation Ruler" plugin itself.

**Comment by Risca** [comment]
I've never written any javascript, but maybe this piece of code is what's causing the issue?
```js
function updateToken(document, changes, _options, _userId) {
  ...
  if ( ruler.active && ruler.token === token ) token._lastMoveDistance = ruler.totalMoveDistance;
  else token._lastMoveDistance = Ruler.measureMoveDistance(token.position, token.document._source, { token }).moveDistance;
  if ( game.combat?.started ) {
    ...
    if ( combatData.lastRound < game.combat.round ) combatData.lastMoveDistance = token._lastMoveDistance;
    else combatData.lastMoveDistance += token._lastMoveDistance;
    combatData.lastRound = game.combat.round;
  }
```
I don't know how often `updateToken()` gets called, but if gets called multiple times in the same round then it looks like it may do
```js
// First call
token._lastMoveDistance = ruler.totalMoveDistance;
combatData.lastMoveDistance = token._lastMoveDistance;

// second call
token._lastMoveDistance = ruler.totalMoveDistance;
combatData.lastMoveDistance += token._lastMoveDistance;
```
Someone better versed in `js` would have to correct me if I'm wrong

**Comment by SoupcanAnthill** [comment]
I updated to the most recent versions of everything, and the issue still persists.
Foundry v12.330
PF2E 6.1.3
Elevation Ruler 0.9.11

It seems to only happen when creating waypoints, including automatic waypoints created when pathfinding.
