### ISSUE TITLE
[Feature] Press Right button to create midpoints for an exact movement turns

### ISSUE THREAD

**Issue by apoapostolov** [caewok/fvtt-elevation-ruler#99]
Something available from Drag Ruler was that with either ENTER or right click you can create midpoints for a complex movement route where exact location is important to be shown to players.

**Comment by caewok** [comment]
Elevation Ruler currently defined keybinds to set waypoints when using the ruler or dragging tokens. Default settings are "=" and "-" for add/remove, respectively. But I hear you about wanting to right-click.

**Comment by apoapostolov** [comment]
Thank you for considering the right click option.

**Comment by caewok** [comment]
Added in v0.9.5. Also check out the additional keybindings; I separated Token Ruler from regular ruler keybindings for adding waypoints.
